// (C) Generated by Claude

using LinkedInOptimizer.Application.Common.Interfaces;
using LinkedInOptimizer.Domain.Exceptions;
using MediatR;

namespace LinkedInOptimizer.Application.Payments;

public record HandlePaystackWebhookCommand(
    string RawBody,
    string Signature,
    string EventType,
    string Reference) : IRequest;

public class HandlePaystackWebhookCommandHandler : IRequestHandler<HandlePaystackWebhookCommand>
{
    private readonly IPaystackClient _paystackClient;
    private readonly IPaymentRepository _paymentRepository;
    private readonly IUserRepository _userRepository;
    private readonly IUnitOfWork _unitOfWork;

    public HandlePaystackWebhookCommandHandler(
        IPaystackClient paystackClient,
        IPaymentRepository paymentRepository,
        IUserRepository userRepository,
        IUnitOfWork unitOfWork)
    {
        _paystackClient = paystackClient;
        _paymentRepository = paymentRepository;
        _userRepository = userRepository;
        _unitOfWork = unitOfWork;
    }

    public async Task Handle(HandlePaystackWebhookCommand command, CancellationToken ct)
    {
        bool valid = _paystackClient.VerifyWebhookSignature(command.RawBody, command.Signature);
        if (!valid)
            throw new BusinessRuleViolationException("Invalid webhook signature.");

        if (command.EventType != "charge.success")
            return;

        var payment = await _paymentRepository.GetByReferenceAsync(command.Reference, ct);
        if (payment is null)
            return;

        if (payment.Status != "pending")
            return;

        payment.MarkSuccess();

        var user = await _userRepository.GetByIdAsync(payment.UserId, ct)
            ?? throw new ResourceNotFoundException("User", payment.UserId);

        user.UpgradeToPremium();

        await _unitOfWork.SaveChangesAsync(ct);
    }
}
