// (C) Generated by Claude

using LinkedInOptimizer.Application.Common.Dtos;
using LinkedInOptimizer.Application.Common.Interfaces;
using LinkedInOptimizer.Application.Common.Options;
using LinkedInOptimizer.Domain.Entities;
using MediatR;
using Microsoft.Extensions.Options;

namespace LinkedInOptimizer.Application.Payments;

public record InitializePaymentCommand(Guid UserId, string Email) : IRequest<PaymentInitDto>;

public class InitializePaymentCommandHandler
    : IRequestHandler<InitializePaymentCommand, PaymentInitDto>
{
    private readonly IPaystackClient _paystackClient;
    private readonly IPaymentRepository _paymentRepository;
    private readonly IUnitOfWork _unitOfWork;
    private readonly PaystackOptions _paystackOptions;

    public InitializePaymentCommandHandler(
        IPaystackClient paystackClient,
        IPaymentRepository paymentRepository,
        IUnitOfWork unitOfWork,
        IOptions<PaystackOptions> paystackOptions)
    {
        _paystackClient = paystackClient;
        _paymentRepository = paymentRepository;
        _unitOfWork = unitOfWork;
        _paystackOptions = paystackOptions.Value;
    }

    public async Task<PaymentInitDto> Handle(
        InitializePaymentCommand command,
        CancellationToken cancellationToken)
    {
        var result = await _paystackClient.InitializeTransactionAsync(
            command.Email,
            _paystackOptions.AmountKobo,
            cancellationToken);

        var payment = Payment.Create(
            command.UserId,
            result.Reference,
            _paystackOptions.AmountKobo,
            "NGN");

        await _paymentRepository.AddAsync(payment, cancellationToken);
        await _unitOfWork.SaveChangesAsync(cancellationToken);

        return new PaymentInitDto(result.AuthorizationUrl, result.Reference);
    }
}
