// (C) Generated by Claude

using FluentValidation;

namespace LinkedInOptimizer.Application.Payments;

public class InitializePaymentCommandValidator : AbstractValidator<InitializePaymentCommand>
{
    public InitializePaymentCommandValidator()
    {
        RuleFor(x => x.Email)
            .NotEmpty()
            .EmailAddress();

        RuleFor(x => x.UserId)
            .NotEqual(Guid.Empty);
    }
}
