// (C) Generated by Claude

using LinkedInOptimizer.Application.Common.Interfaces;
using LinkedInOptimizer.Domain.Exceptions;
using MediatR;

namespace LinkedInOptimizer.Application.Payments;

public record VerifyPaymentCommand(Guid UserId, string Reference) : IRequest;

public class VerifyPaymentCommandHandler : IRequestHandler<VerifyPaymentCommand>
{
    private readonly IPaystackClient _paystackClient;
    private readonly IPaymentRepository _paymentRepository;
    private readonly IUserRepository _userRepository;
    private readonly IUnitOfWork _unitOfWork;

    public VerifyPaymentCommandHandler(
        IPaystackClient paystackClient,
        IPaymentRepository paymentRepository,
        IUserRepository userRepository,
        IUnitOfWork unitOfWork)
    {
        _paystackClient = paystackClient;
        _paymentRepository = paymentRepository;
        _userRepository = userRepository;
        _unitOfWork = unitOfWork;
    }

    public async Task Handle(VerifyPaymentCommand command, CancellationToken ct)
    {
        var result = await _paystackClient.VerifyTransactionAsync(command.Reference, ct);

        if (result.Status == "success")
        {
            var payment = await _paymentRepository.GetByReferenceAsync(command.Reference, ct)
                ?? throw new ResourceNotFoundException("Payment", command.Reference);

            payment.MarkSuccess();

            var user = await _userRepository.GetByIdAsync(payment.UserId, ct)
                ?? throw new ResourceNotFoundException("User", payment.UserId);

            user.UpgradeToPremium();

            await _unitOfWork.SaveChangesAsync(ct);
        }
    }
}
