// (C) Generated by Claude

using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using LinkedInOptimizer.Application.Common.Interfaces;
using LinkedInOptimizer.Domain.ValueObjects;

namespace LinkedInOptimizer.Api.Services;

public class CurrentUserService : ICurrentUser
{
    private readonly IHttpContextAccessor _httpContextAccessor;

    public CurrentUserService(IHttpContextAccessor httpContextAccessor)
    {
        _httpContextAccessor = httpContextAccessor;
    }

    private ClaimsPrincipal GetAuthenticatedUser()
    {
        var httpContext = _httpContextAccessor.HttpContext;

        if (httpContext is null || httpContext.User.Identity?.IsAuthenticated != true)
            throw new InvalidOperationException("User is not authenticated.");

        return httpContext.User;
    }

    public Guid UserId
    {
        get
        {
            var user = GetAuthenticatedUser();
            var claim = user.FindFirstValue(ClaimTypes.NameIdentifier);

            if (claim is null || !Guid.TryParse(claim, out var userId))
                throw new InvalidOperationException("User is not authenticated.");

            return userId;
        }
    }

    public string Email
    {
        get
        {
            var user = GetAuthenticatedUser();
            return user.FindFirstValue(ClaimTypes.Email)
                ?? user.FindFirstValue(JwtRegisteredClaimNames.Email)
                ?? throw new InvalidOperationException("User is not authenticated.");
        }
    }

    public Tier Tier
    {
        get
        {
            var user = GetAuthenticatedUser();
            var tierClaim = user.FindFirstValue("tier");
            return tierClaim == "premium" ? Tier.Premium : Tier.Free;
        }
    }
}
