// (C) Generated by Claude

using LinkedInOptimizer.Application.Common.Dtos;
using LinkedInOptimizer.Application.Common.Interfaces;
using LinkedInOptimizer.Domain.Entities;
using LinkedInOptimizer.Domain.Exceptions;
using MediatR;

namespace LinkedInOptimizer.Application.Profiles;

public record IngestProfileCommand(Guid UserId, string LinkedInUrl, string RawText)
    : IRequest<ProfileDto>;

public class IngestProfileCommandHandler
    : IRequestHandler<IngestProfileCommand, ProfileDto>
{
    private readonly IProfileRepository _profileRepository;
    private readonly IProfileTextParser _profileTextParser;
    private readonly IUnitOfWork _unitOfWork;

    public IngestProfileCommandHandler(
        IProfileRepository profileRepository,
        IProfileTextParser profileTextParser,
        IUnitOfWork unitOfWork)
    {
        _profileRepository = profileRepository;
        _profileTextParser = profileTextParser;
        _unitOfWork = unitOfWork;
    }

    public async Task<ProfileDto> Handle(
        IngestProfileCommand command,
        CancellationToken cancellationToken)
    {
        if (command.RawText.Length < 50)
            throw new DomainValidationException(
                "ProfileText",
                "Profile text is too short to analyze.");

        if (!command.LinkedInUrl.StartsWith(
                "https://www.linkedin.com/in/",
                StringComparison.OrdinalIgnoreCase))
            throw new DomainValidationException(
                "LinkedInUrl",
                "LinkedIn URL must begin with https://www.linkedin.com/in/.");

        var parsedJson = _profileTextParser.Parse(command.RawText);

        var profile = Profile.Create(
            command.UserId,
            command.LinkedInUrl,
            command.RawText,
            parsedJson);

        await _profileRepository.AddAsync(profile, cancellationToken);
        await _unitOfWork.SaveChangesAsync(cancellationToken);

        return new ProfileDto(profile.Id, profile.LinkedInUrl, profile.IngestedAt);
    }
}
