// (C) Generated by Claude

using FluentValidation;

namespace LinkedInOptimizer.Application.Profiles;

public class IngestProfileCommandValidator : AbstractValidator<IngestProfileCommand>
{
    public IngestProfileCommandValidator()
    {
        RuleFor(x => x.RawText)
            .NotEmpty();

        RuleFor(x => x.LinkedInUrl)
            .NotEmpty();

        RuleFor(x => x.UserId)
            .NotEqual(Guid.Empty);
    }
}
