// (C) Generated by Claude

using System.Text;
using System.Text.Json;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Wordprocessing;
using LinkedInOptimizer.Application.Common.Interfaces;

namespace LinkedInOptimizer.Infrastructure.Parsing;

public sealed class DocxCvParser : ICvParser
{
    public Task<string> ParseAsync(Stream fileStream, CancellationToken ct)
    {
        var lines = ExtractLines(fileStream);
        var roles = ParseRoles(lines);
        var json = JsonSerializer.Serialize(new { roles });
        return Task.FromResult(json);
    }

    // ── Text extraction ──────────────────────────────────────────────────────

    private static List<string> ExtractLines(Stream stream)
    {
        using var document = WordprocessingDocument.Open(stream, isEditable: false);
        var body = document.MainDocumentPart?.Document?.Body;
        if (body is null)
            return [];

        var lines = new List<string>();
        foreach (var paragraph in body.Elements<Paragraph>())
        {
            var sb = new StringBuilder();
            foreach (var run in paragraph.Elements<Run>())
            {
                foreach (var text in run.Elements<Text>())
                    sb.Append(text.Text);
            }

            var line = sb.ToString().Trim();
            if (line.Length > 0)
                lines.Add(line);
        }

        return lines;
    }

    // ── Heuristic role parsing ───────────────────────────────────────────────

    private static List<Role> ParseRoles(List<string> lines)
    {
        var roles = new List<Role>();
        Role? current = null;

        for (var i = 0; i < lines.Count; i++)
        {
            var line = lines[i];

            if (IsBullet(line))
            {
                // Ensure there is a role to attach bullets to
                current ??= new Role { Title = string.Empty, Company = string.Empty };
                current.Bullets.Add(StripBulletPrefix(line));
                continue;
            }

            if (IsRoleHeader(line))
            {
                if (current is not null)
                    roles.Add(current);

                // Peek at the next non-bullet line as the company name
                var company = string.Empty;
                if (i + 1 < lines.Count && !IsRoleHeader(lines[i + 1]) && !IsBullet(lines[i + 1]))
                {
                    company = lines[i + 1];
                    i++; // consume the company line
                }

                current = new Role { Title = line, Company = company };
                continue;
            }

            // Plain line that is neither a header nor a bullet — treat as
            // a bullet under the current role (catches summary paragraphs, etc.)
            if (current is not null)
                current.Bullets.Add(line);
        }

        if (current is not null)
            roles.Add(current);

        // Fallback: if heuristics found nothing, wrap everything as bullets
        if (roles.Count == 0 && lines.Count > 0)
        {
            roles.Add(new Role
            {
                Title = string.Empty,
                Company = string.Empty,
                Bullets = lines
            });
        }

        return roles;
    }

    // ── Heuristic helpers ────────────────────────────────────────────────────

    /// <summary>
    /// A role header is a short (≤60 chars), title-case-ish line that contains
    /// no sentence-ending punctuation and no bullet markers.
    /// </summary>
    private static bool IsRoleHeader(string line)
    {
        if (line.Length > 60)
            return false;

        if (IsBullet(line))
            return false;

        // Must not end with sentence punctuation
        if (line.EndsWith('.') || line.EndsWith(',') || line.EndsWith(';'))
            return false;

        // At least one word must start with an uppercase letter
        var words = line.Split(' ', StringSplitOptions.RemoveEmptyEntries);
        if (words.Length == 0)
            return false;

        var uppercaseWords = words.Count(w => w.Length > 0 && char.IsUpper(w[0]));
        return uppercaseWords >= 1;
    }

    private static bool IsBullet(string line)
    {
        if (line.StartsWith('•') || line.StartsWith('-') || line.StartsWith('*'))
            return true;

        // Numbered bullet: "1." / "1)" / "1 "
        if (line.Length >= 2 && char.IsDigit(line[0]) &&
            (line[1] == '.' || line[1] == ')' || line[1] == ' '))
            return true;

        return false;
    }

    private static string StripBulletPrefix(string line)
    {
        if (line.StartsWith('•') || line.StartsWith('-') || line.StartsWith('*'))
            return line[1..].TrimStart();

        if (line.Length >= 2 && char.IsDigit(line[0]) &&
            (line[1] == '.' || line[1] == ')' || line[1] == ' '))
            return line[2..].TrimStart();

        return line;
    }

    // ── DTO ──────────────────────────────────────────────────────────────────

    private sealed class Role
    {
        public string Title { get; set; } = string.Empty;
        public string Company { get; set; } = string.Empty;
        public List<string> Bullets { get; set; } = [];
    }
}
