// (C) Generated by Claude

using System.Text.Json;
using System.Text.RegularExpressions;
using LinkedInOptimizer.Application.Common.Interfaces;
using UglyToad.PdfPig;

namespace LinkedInOptimizer.Infrastructure.Parsing;

public class PdfCvParser : ICvParser
{
    private static readonly Regex BulletPattern =
        new(@"^(\u2022|-|\*|\d+\.)\s+", RegexOptions.Compiled);

    private static readonly Regex TitleCasePattern =
        new(@"^[A-Z][a-z]+(\s+[A-Z][a-z]+)*$", RegexOptions.Compiled);

    private static readonly Regex AllCapsPattern =
        new(@"^[A-Z][A-Z\s]+$", RegexOptions.Compiled);

    private static readonly Regex PunctuationPattern =
        new(@"[,;:!?""'()\[\]{}]", RegexOptions.Compiled);

    public Task<string> ParseAsync(Stream fileStream, CancellationToken ct)
    {
        var roles = ExtractRoles(fileStream);
        var json = JsonSerializer.Serialize(new { roles });
        return Task.FromResult(json);
    }

    private static List<RoleEntry> ExtractRoles(Stream fileStream)
    {
        var lines = ExtractLines(fileStream);

        if (lines.Count == 0)
            return FallbackRoles(lines);

        var roles = ParseRoles(lines);

        return roles.Count > 0 ? roles : FallbackRoles(lines);
    }

    private static List<string> ExtractLines(Stream fileStream)
    {
        var lines = new List<string>();

        using var document = PdfDocument.Open(fileStream);
        foreach (var page in document.GetPages())
        {
            var pageText = page.Text;
            if (string.IsNullOrWhiteSpace(pageText))
                continue;

            var pageLines = pageText
                .Split(new[] { '\n', '\r' }, StringSplitOptions.None)
                .Select(l => l.Trim())
                .Where(l => l.Length > 0);

            lines.AddRange(pageLines);
        }

        return lines;
    }

    private static List<RoleEntry> ParseRoles(List<string> lines)
    {
        var roles = new List<RoleEntry>();
        RoleEntry? current = null;

        for (int i = 0; i < lines.Count; i++)
        {
            var line = lines[i];

            if (IsBulletLine(line))
            {
                if (current != null)
                    current.Bullets.Add(StripBulletPrefix(line));
                continue;
            }

            if (LooksLikeJobTitle(line) && i + 1 < lines.Count)
            {
                var nextLine = lines[i + 1];
                if (!IsBulletLine(nextLine) && !LooksLikeJobTitle(nextLine) && nextLine.Length > 0)
                {
                    // Commit previous role
                    if (current != null)
                        roles.Add(current);

                    current = new RoleEntry
                    {
                        Title = line,
                        Company = nextLine
                    };

                    i++; // skip the company line
                    continue;
                }
            }

            // Non-bullet, non-title line — treat as bullet under current role if one is open
            if (current != null && line.Length > 0)
                current.Bullets.Add(line);
        }

        if (current != null)
            roles.Add(current);

        return roles;
    }

    private static List<RoleEntry> FallbackRoles(List<string> lines)
    {
        return new List<RoleEntry>
        {
            new RoleEntry
            {
                Title = "Unknown",
                Company = "Unknown",
                Bullets = lines.Where(l => l.Length > 0).ToList()
            }
        };
    }

    private static bool LooksLikeJobTitle(string line)
    {
        if (line.Length == 0 || line.Length > 60)
            return false;

        if (PunctuationPattern.IsMatch(line))
            return false;

        return AllCapsPattern.IsMatch(line) || TitleCasePattern.IsMatch(line);
    }

    private static bool IsBulletLine(string line) =>
        BulletPattern.IsMatch(line);

    private static string StripBulletPrefix(string line) =>
        BulletPattern.Replace(line, string.Empty).Trim();

    private sealed class RoleEntry
    {
        public string Title { get; set; } = string.Empty;
        public string Company { get; set; } = string.Empty;
        public List<string> Bullets { get; set; } = new();
    }
}
