// (C) Generated by Claude

using System.Text.Json;
using LinkedInOptimizer.Application.Common.Interfaces;

namespace LinkedInOptimizer.Infrastructure.Parsing;

public class ProfileTextParser : IProfileTextParser
{
    // Section headers recognised in LinkedIn paste format (lower-cased for comparison)
    private static readonly HashSet<string> SectionHeaders = new(StringComparer.OrdinalIgnoreCase)
    {
        "about",
        "experience",
        "education",
        "skills",
        "certifications",
        "licenses & certifications"
    };

    // Characters that indicate a bullet point line
    private static readonly char[] BulletChars = { '•', '-', '*', '·', '–', '—' };

    // Simple date-range patterns (e.g. "Jan 2020 – Present", "2018 - 2021")
    private static readonly string[] MonthAbbreviations =
    {
        "jan", "feb", "mar", "apr", "may", "jun",
        "jul", "aug", "sep", "oct", "nov", "dec"
    };

    public string Parse(string rawText)
    {
        if (string.IsNullOrWhiteSpace(rawText))
        {
            return SerializeResult(string.Empty, string.Empty, Array.Empty<ExperienceEntry>(), Array.Empty<string>());
        }

        var lines = rawText
            .Split('\n')
            .Select(l => l.TrimEnd('\r').Trim())
            .ToList();

        // --- headline: first non-empty line that is not itself a section header ---
        string headline = string.Empty;
        int headlineIndex = -1;
        for (int i = 0; i < lines.Count; i++)
        {
            if (!string.IsNullOrWhiteSpace(lines[i]) && !IsSectionHeader(lines[i]))
            {
                headline = lines[i];
                headlineIndex = i;
                break;
            }
        }

        // --- bucket lines into sections ---
        var sections = new Dictionary<string, List<string>>(StringComparer.OrdinalIgnoreCase);
        string? currentSection = null;

        for (int i = headlineIndex + 1; i < lines.Count; i++)
        {
            var line = lines[i];
            if (IsSectionHeader(line))
            {
                // Normalise "Licenses & certifications" → "certifications" bucket
                currentSection = NormaliseSectionKey(line);
                if (!sections.ContainsKey(currentSection))
                    sections[currentSection] = new List<string>();
            }
            else if (currentSection != null)
            {
                sections[currentSection].Add(line);
            }
        }

        // --- about ---
        string about = string.Empty;
        if (sections.TryGetValue("about", out var aboutLines))
        {
            about = string.Join("\n", aboutLines).Trim();
        }

        // --- experience ---
        var experience = Array.Empty<ExperienceEntry>();
        if (sections.TryGetValue("experience", out var expLines))
        {
            experience = ParseExperience(expLines);
        }

        // --- skills ---
        var skills = Array.Empty<string>();
        if (sections.TryGetValue("skills", out var skillLines))
        {
            skills = ParseSkills(skillLines);
        }

        return SerializeResult(headline, about, experience, skills);
    }

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    private static bool IsSectionHeader(string line) =>
        SectionHeaders.Contains(line.Trim());

    private static string NormaliseSectionKey(string header)
    {
        var lower = header.Trim().ToLowerInvariant();
        if (lower == "licenses & certifications") return "certifications";
        return lower;
    }

    private static ExperienceEntry[] ParseExperience(List<string> lines)
    {
        var roles = new List<ExperienceEntry>();
        ExperienceEntry? current = null;

        foreach (var line in lines)
        {
            if (string.IsNullOrWhiteSpace(line)) continue;

            if (IsNewRoleTitle(line))
            {
                // Flush previous role
                if (current != null) roles.Add(current);

                current = new ExperienceEntry { Title = line };
            }
            else if (current != null)
            {
                if (current.Company == string.Empty && !IsBulletLine(line) && !IsDateRange(line))
                {
                    current.Company = line;
                }
                else if (!IsDateRange(line))
                {
                    // Strip leading bullet character if present
                    var bullet = line.TrimStart(BulletChars).Trim();
                    if (!string.IsNullOrWhiteSpace(bullet))
                        current.Bullets.Add(bullet);
                }
            }
        }

        if (current != null) roles.Add(current);
        return roles.ToArray();
    }

    private static bool IsNewRoleTitle(string line)
    {
        // A new role title: does NOT start with a bullet char and is NOT a date range
        if (IsBulletLine(line)) return false;
        if (IsDateRange(line)) return false;
        return true;
    }

    private static bool IsBulletLine(string line) =>
        line.Length > 0 && BulletChars.Contains(line[0]);

    private static bool IsDateRange(string line)
    {
        var lower = line.ToLowerInvariant();
        // Contains a year-like pattern (4 digits) and either a month abbreviation or "present"
        bool hasYear = System.Text.RegularExpressions.Regex.IsMatch(lower, @"\b\d{4}\b");
        bool hasMonth = MonthAbbreviations.Any(m => lower.Contains(m));
        bool hasPresent = lower.Contains("present");
        return hasYear && (hasMonth || hasPresent);
    }

    private static string[] ParseSkills(List<string> lines)
    {
        var skills = new List<string>();
        foreach (var line in lines)
        {
            // Each line may contain comma-separated skills
            var parts = line.Split(',');
            foreach (var part in parts)
            {
                var trimmed = part.Trim();
                if (!string.IsNullOrWhiteSpace(trimmed))
                    skills.Add(trimmed);
            }
        }
        return skills.ToArray();
    }

    private static string SerializeResult(
        string headline,
        string about,
        ExperienceEntry[] experience,
        string[] skills)
    {
        var result = new
        {
            headline,
            about,
            experience = experience.Select(e => new
            {
                title = e.Title,
                company = e.Company,
                bullets = e.Bullets.ToArray()
            }).ToArray(),
            skills
        };

        return JsonSerializer.Serialize(result, new JsonSerializerOptions
        {
            WriteIndented = false,
            PropertyNamingPolicy = JsonNamingPolicy.CamelCase
        });
    }

    // -------------------------------------------------------------------------
    // Internal model
    // -------------------------------------------------------------------------

    private sealed class ExperienceEntry
    {
        public string Title { get; set; } = string.Empty;
        public string Company { get; set; } = string.Empty;
        public List<string> Bullets { get; } = new();
    }
}
