// (C) Generated by Claude

using System.Text.Json;
using LinkedInOptimizer.Application.Common.Dtos;
using LinkedInOptimizer.Application.Common.Interfaces;
using LinkedInOptimizer.Domain.Exceptions;
using LinkedInOptimizer.Domain.ValueObjects;
using MediatR;

namespace LinkedInOptimizer.Application.Analyses;

public record GetAnalysisQuery(Guid UserId, Guid AnalysisId) : IRequest<AnalysisDto>;

public class GetAnalysisQueryHandler : IRequestHandler<GetAnalysisQuery, AnalysisDto>
{
    private static readonly JsonSerializerOptions _jsonOptions = new()
    {
        PropertyNameCaseInsensitive = true
    };

    private readonly IAnalysisRepository _analysisRepository;
    private readonly IRewriteRepository _rewriteRepository;

    public GetAnalysisQueryHandler(
        IAnalysisRepository analysisRepository,
        IRewriteRepository rewriteRepository)
    {
        _analysisRepository = analysisRepository;
        _rewriteRepository = rewriteRepository;
    }

    public async Task<AnalysisDto> Handle(GetAnalysisQuery query, CancellationToken ct)
    {
        var analysis = await _analysisRepository.GetByIdAsync(query.AnalysisId, ct);

        if (analysis is null || analysis.UserId != query.UserId)
            throw new ResourceNotFoundException("Analysis", query.AnalysisId);

        RewriteDto? rewriteDto = null;

        if (analysis.Status == AnalysisStatus.Complete)
        {
            var rewrite = await _rewriteRepository.GetByAnalysisIdAsync(analysis.Id, ct);

            if (rewrite is not null)
            {
                var bannerData = JsonSerializer.Deserialize<BannerData>(rewrite.BannerJson, _jsonOptions);

                rewriteDto = new RewriteDto(
                    Headlines: JsonSerializer.Deserialize<string[]>(rewrite.HeadlinesJson, _jsonOptions) ?? [],
                    About: JsonSerializer.Deserialize<string[]>(rewrite.AboutJson, _jsonOptions) ?? [],
                    Experience: JsonSerializer.Deserialize<ExperienceSectionDto[]>(rewrite.ExperienceJson, _jsonOptions) ?? [],
                    Skills: JsonSerializer.Deserialize<string[]>(rewrite.SkillsJson, _jsonOptions) ?? [],
                    BannerSuggestion: bannerData?.Suggestion ?? string.Empty,
                    Tips: JsonSerializer.Deserialize<string[]>(rewrite.TipsJson, _jsonOptions) ?? []
                );
            }
        }

        var problems = JsonSerializer.Deserialize<string[]>(analysis.ProblemsJson, _jsonOptions) ?? [];

        return new AnalysisDto(
            analysis.Id,
            analysis.Score.Value,
            problems,
            analysis.Status.Value.ToString().ToLowerInvariant(),
            rewriteDto);
    }

    private record BannerData(string? Suggestion);
}
