// (C) Generated by Claude

using System.Text.Json;
using Hangfire;
using MediatR;
using LinkedInOptimizer.Application.Common.Dtos;
using LinkedInOptimizer.Application.Common.Interfaces;
using LinkedInOptimizer.Application.Scoring;
using LinkedInOptimizer.Domain.Entities;
using LinkedInOptimizer.Domain.Exceptions;

namespace LinkedInOptimizer.Application.Analyses;

public record StartAnalysisCommand(Guid UserId, Guid ProfileId, Guid CvId)
    : IRequest<AnalysisDto>;

public class StartAnalysisCommandHandler
    : IRequestHandler<StartAnalysisCommand, AnalysisDto>
{
    private readonly IProfileRepository _profileRepository;
    private readonly ICvRepository _cvRepository;
    private readonly IAnalysisRepository _analysisRepository;
    private readonly IUnitOfWork _unitOfWork;
    private readonly ICurrentUser _currentUser;
    private readonly ProfileScorer _profileScorer;

    public StartAnalysisCommandHandler(
        IProfileRepository profileRepository,
        ICvRepository cvRepository,
        IAnalysisRepository analysisRepository,
        IUnitOfWork unitOfWork,
        ICurrentUser currentUser,
        ProfileScorer profileScorer)
    {
        _profileRepository  = profileRepository;
        _cvRepository       = cvRepository;
        _analysisRepository = analysisRepository;
        _unitOfWork         = unitOfWork;
        _currentUser        = currentUser;
        _profileScorer      = profileScorer;
    }

    public async Task<AnalysisDto> Handle(
        StartAnalysisCommand command, CancellationToken ct)
    {
        // 1. Load Profile
        var profile = await _profileRepository.GetByIdAsync(command.ProfileId, ct);
        if (profile is null || profile.UserId != command.UserId)
            throw new ResourceNotFoundException("Profile", command.ProfileId);

        // 2. Load CV
        var cv = await _cvRepository.GetByIdAsync(command.CvId, ct);
        if (cv is null || cv.UserId != command.UserId)
            throw new ResourceNotFoundException("Cv", command.CvId);

        // 3. Score
        var (score, problems) = _profileScorer.Score(profile.ParsedJson, cv.ParsedJson);

        // 4. Serialize problems
        var problemsJson = JsonSerializer.Serialize(problems);

        // 5. Create aggregate
        var analysis = Analysis.Create(
            command.UserId, command.ProfileId, command.CvId, score, problemsJson);

        // 6. Persist
        await _analysisRepository.AddAsync(analysis, ct);

        // 7. Save
        await _unitOfWork.SaveChangesAsync(ct);

        // 8. Enqueue rewrite job for premium users
        if (_currentUser.Tier.IsPremium)
            BackgroundJob.Enqueue<IGenerateRewriteJob>(j => j.Run(analysis.Id));

        // 9. Return DTO
        return new AnalysisDto(
            analysis.Id,
            analysis.Score.Value,
            problems,
            analysis.Status.Value.ToString().ToLowerInvariant(),
            null);
    }
}
