// (C) Generated by Claude

using FluentValidation;

namespace LinkedInOptimizer.Application.Analyses;

public class StartAnalysisCommandValidator : AbstractValidator<StartAnalysisCommand>
{
    public StartAnalysisCommandValidator()
    {
        RuleFor(x => x.ProfileId)
            .NotEqual(Guid.Empty);

        RuleFor(x => x.CvId)
            .NotEqual(Guid.Empty);

        RuleFor(x => x.UserId)
            .NotEqual(Guid.Empty);
    }
}
