# (C) Generated by Claude
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copy solution and project files
COPY LinkedInOptimizer.sln .
COPY src/LinkedInOptimizer.Domain/LinkedInOptimizer.Domain.csproj src/LinkedInOptimizer.Domain/
COPY src/LinkedInOptimizer.Application/LinkedInOptimizer.Application.csproj src/LinkedInOptimizer.Application/
COPY src/LinkedInOptimizer.Infrastructure/LinkedInOptimizer.Infrastructure.csproj src/LinkedInOptimizer.Infrastructure/
COPY src/LinkedInOptimizer.Api/LinkedInOptimizer.Api.csproj src/LinkedInOptimizer.Api/
COPY tests/LinkedInOptimizer.UnitTests/LinkedInOptimizer.UnitTests.csproj tests/LinkedInOptimizer.UnitTests/

# Restore
RUN dotnet restore src/LinkedInOptimizer.Api/LinkedInOptimizer.Api.csproj

# Copy everything and publish
COPY . .
RUN dotnet publish src/LinkedInOptimizer.Api/LinkedInOptimizer.Api.csproj \
    -c Release \
    -o /app/publish \
    --no-restore

# Runtime image
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .

ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 8080

ENTRYPOINT ["dotnet", "LinkedInOptimizer.Api.dll"]
