// (C) Generated by Claude

using System.Text.Json;
using Hangfire;
using LinkedInOptimizer.Application.Common.Interfaces;
using LinkedInOptimizer.Infrastructure.Persistence;

namespace LinkedInOptimizer.Infrastructure.BackgroundJobs;

[AutomaticRetry(Attempts = 3)]
public class GenerateRewriteJob : IGenerateRewriteJob
{
    private readonly AppDbContext _db;
    private readonly IClaudeClient _claude;

    public GenerateRewriteJob(AppDbContext db, IClaudeClient claude)
    {
        _db = db;
        _claude = claude;
    }

    public async Task Run(Guid analysisId)
    {
        var analysis = await _db.Analyses.FindAsync(analysisId)
            ?? throw new InvalidOperationException($"Analysis {analysisId} not found.");

        var profile = await _db.Profiles.FindAsync(analysis.ProfileId)
            ?? throw new InvalidOperationException($"Profile {analysis.ProfileId} not found.");

        var cv = await _db.Cvs.FindAsync(analysis.CvId)
            ?? throw new InvalidOperationException($"CV {analysis.CvId} not found.");

        analysis.MarkGenerating();
        await _db.SaveChangesAsync();

        try
        {
            var results = await Task.WhenAll(
                _claude.GenerateHeadlinesAsync(profile.ParsedJson, cv.ParsedJson, CancellationToken.None),
                _claude.GenerateAboutAsync(profile.ParsedJson, cv.ParsedJson, CancellationToken.None),
                _claude.GenerateExperienceAsync(profile.ParsedJson, cv.ParsedJson, CancellationToken.None),
                _claude.GenerateAddonsAsync(profile.ParsedJson, cv.ParsedJson, CancellationToken.None)
            );

            var addonsJson = results[3];
            using var doc = JsonDocument.Parse(addonsJson);
            var root = doc.RootElement;

            var skillsJson = root.GetProperty("skills").GetRawText();
            var bannerJson = root.GetProperty("banner").GetRawText();
            var tipsJson = root.GetProperty("tips").GetRawText();

            var rewrite = Domain.Entities.Rewrite.Create(
                analysisId,
                headlinesJson: results[0],
                aboutJson: results[1],
                experienceJson: results[2],
                skillsJson: skillsJson,
                bannerJson: bannerJson,
                tipsJson: tipsJson
            );

            _db.Rewrites.Add(rewrite);
            analysis.MarkComplete();
            await _db.SaveChangesAsync();
        }
        catch
        {
            analysis.MarkFailed();
            await _db.SaveChangesAsync();
            throw;
        }
    }
}
