// (C) Generated by Claude

using Hangfire;
using Hangfire.PostgreSql;
using LinkedInOptimizer.Application.Common.Interfaces;
using LinkedInOptimizer.Infrastructure.Ai;
using LinkedInOptimizer.Infrastructure.Auth;
using LinkedInOptimizer.Infrastructure.BackgroundJobs;
using LinkedInOptimizer.Infrastructure.Options;
using LinkedInOptimizer.Infrastructure.Parsing;
using LinkedInOptimizer.Infrastructure.Payments;
using LinkedInOptimizer.Infrastructure.Persistence;
using LinkedInOptimizer.Infrastructure.Persistence.Repositories;
using LinkedInOptimizer.Infrastructure.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;

namespace LinkedInOptimizer.Infrastructure;

public static class InfrastructureServiceCollectionExtensions
{
    public static IServiceCollection AddInfrastructure(
        this IServiceCollection services,
        IConfiguration configuration)
    {
        // EF Core + Npgsql
        services.AddDbContext<AppDbContext>(opts =>
            opts.UseNpgsql(configuration.GetConnectionString("Default")));

        // Unit of Work
        services.AddScoped<IUnitOfWork, UnitOfWork>();

        // Repositories
        services.AddScoped<IUserRepository, UserRepository>();
        services.AddScoped<ICvRepository, CvRepository>();
        services.AddScoped<IProfileRepository, ProfileRepository>();
        services.AddScoped<IAnalysisRepository, AnalysisRepository>();
        services.AddScoped<IRewriteRepository, RewriteRepository>();
        services.AddScoped<IPaymentRepository, PaymentRepository>();

        // Auth
        services.AddScoped<IPasswordHasher, BcryptPasswordHasher>();
        services.AddScoped<IJwtTokenService, JwtTokenService>();

        // Parsers
        services.AddScoped<IProfileTextParser, ProfileTextParser>();
        services.AddKeyedScoped<ICvParser, PdfCvParser>("pdf");
        services.AddKeyedScoped<ICvParser, DocxCvParser>("docx");

        // External adapters
        services.AddHttpClient();
        services.AddScoped<IClaudeClient, ClaudeClient>();
        services.AddScoped<ICloudinaryClient, CloudinaryClient>();
        services.AddScoped<IPaystackClient, PaystackClient>();

        // Background jobs
        services.AddHangfire(cfg =>
            cfg.UsePostgreSqlStorage(c =>
                c.UseNpgsqlConnection(configuration.GetConnectionString("Default"))));
        services.AddHangfireServer(opts => opts.WorkerCount = 4);
        services.AddScoped<IGenerateRewriteJob, GenerateRewriteJob>();

        // Options
        services.Configure<JwtOptions>(configuration.GetSection("Jwt"));
        services.Configure<AnthropicOptions>(configuration.GetSection("Anthropic"));
        services.Configure<CloudinaryOptions>(configuration.GetSection("Cloudinary"));
        services.Configure<PaystackOptions>(configuration.GetSection("Paystack"));

        return services;
    }
}
