// (C) Generated by Claude

using LinkedInOptimizer.Application;
using LinkedInOptimizer.Infrastructure;
using LinkedInOptimizer.Infrastructure.Persistence;
using LinkedInOptimizer.Api;
using Hangfire;
using AspNetCoreRateLimit;
using Serilog;
using Microsoft.EntityFrameworkCore;

// Serilog bootstrap logger
Log.Logger = new LoggerConfiguration()
    .WriteTo.Console()
    .CreateBootstrapLogger();

try
{
    var builder = WebApplication.CreateBuilder(args);

    // Serilog
    builder.Host.UseSerilog((ctx, lc) => lc
        .ReadFrom.Configuration(ctx.Configuration)
        .WriteTo.Console());

    // Register layers
    builder.Services
        .AddApplication()
        .AddInfrastructure(builder.Configuration)
        .AddApiServices(builder.Configuration);

    // Register ProfileScorer as scoped (needed by StartAnalysisCommandHandler)
    builder.Services.AddScoped<LinkedInOptimizer.Application.Scoring.ProfileScorer>();

    var app = builder.Build();

    // Auto-migrate on startup
    using (var scope = app.Services.CreateScope())
    {
        var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
        await db.Database.MigrateAsync();
    }

    // Middleware pipeline
    app.UseMiddleware<LinkedInOptimizer.Api.Middleware.ExceptionHandlingMiddleware>();

    if (app.Environment.IsDevelopment())
    {
        app.UseSwagger();
        app.UseSwaggerUI();
    }

    app.UseIpRateLimiting();
    app.UseCors("Frontend");
    app.UseAuthentication();
    app.UseAuthorization();

    app.MapControllers();

    // Hangfire dashboard (admin only in production — simplified for MVP)
    app.UseHangfireDashboard("/hangfire");

    await app.RunAsync();
}
catch (Exception ex)
{
    Log.Fatal(ex, "Application startup failed.");
}
finally
{
    Log.CloseAndFlush();
}
