// (C) Generated by Claude

namespace LinkedInOptimizer.Application.Common.Dtos;

public record AnalysisDto(
    Guid Id,
    int Score,
    string[] Problems,
    string Status,
    RewriteDto? Rewrite);
