// (C) Generated by Claude
// Paystack infrastructure result DTOs — consumed by IPaystackClient.
// Full DTO set is defined in task 2.2.

namespace LinkedInOptimizer.Application.Common.Dtos;

public record PaystackInitResult(string AuthorizationUrl, string Reference);
public record PaystackVerifyResult(string Status, int Amount, string Currency);
