// (C) Generated by Claude

namespace LinkedInOptimizer.Application.Common.Dtos;

public record RewriteDto(
    string[] Headlines,
    string[] About,
    ExperienceSectionDto[] Experience,
    string[] Skills,
    string BannerSuggestion,
    string[] Tips);
