// (C) Generated by Claude
using CloudinaryDotNet;
using CloudinaryDotNet.Actions;
using LinkedInOptimizer.Application.Common.Interfaces;
using LinkedInOptimizer.Application.Common.Options;
using Microsoft.Extensions.Options;

namespace LinkedInOptimizer.Infrastructure.Storage;

public sealed class CloudinaryClient : ICloudinaryClient
{
    private readonly Cloudinary _cloudinary;

    public CloudinaryClient(IOptions<CloudinaryOptions> options)
    {
        var opts = options.Value;
        _cloudinary = new Cloudinary(new Account(opts.CloudName, opts.ApiKey, opts.ApiSecret));
    }

    public async Task<string> UploadRawAsync(Stream fileStream, string filename, CancellationToken ct)
    {
        var uploadParams = new RawUploadParams
        {
            File = new FileDescription(filename, fileStream)
        };

        var result = await _cloudinary.UploadAsync(uploadParams, "raw", ct);

        if (result.Error != null)
            throw new InvalidOperationException($"Cloudinary upload failed: {result.Error.Message}");

        return result.PublicId;
    }

    public async Task DeleteAsync(string publicId, CancellationToken ct)
    {
        var deletionParams = new DeletionParams(publicId)
        {
            ResourceType = ResourceType.Raw
        };

        await _cloudinary.DestroyAsync(deletionParams);
    }
}
