// (C) Generated by Claude

using FluentValidation;
using MediatR;
using Microsoft.Extensions.DependencyInjection;
using LinkedInOptimizer.Application.Common.Behaviors;

namespace LinkedInOptimizer.Application;

/// <summary>
/// Marker class used solely for assembly scanning (MediatR + FluentValidation).
/// </summary>
internal sealed class ApplicationAssemblyMarker { }

/// <summary>
/// Extension methods for registering Application-layer services.
/// </summary>
public static class ApplicationServiceCollectionExtensions
{
    public static IServiceCollection AddApplication(this IServiceCollection services)
    {
        services.AddMediatR(cfg =>
        {
            cfg.RegisterServicesFromAssemblyContaining<ApplicationAssemblyMarker>();
            cfg.AddOpenBehavior(typeof(ValidationBehavior<,>));
        });

        services.AddValidatorsFromAssemblyContaining<ApplicationAssemblyMarker>();

        return services;
    }
}
