// (C) Generated by Claude

namespace LinkedInOptimizer.Domain.Exceptions;

public class BusinessRuleViolationException : Exception
{
    public BusinessRuleViolationException(string message) : base(message) { }
    public BusinessRuleViolationException(string message, Exception inner) : base(message, inner) { }
}
