// (C) Generated by Claude

namespace LinkedInOptimizer.Domain.Exceptions;

public class DomainValidationException : Exception
{
    public IDictionary<string, string[]> Errors { get; }

    public DomainValidationException(string property, string error)
        : base($"Validation failed: {property} — {error}")
    {
        Errors = new Dictionary<string, string[]> { [property] = [error] };
    }

    public DomainValidationException(IDictionary<string, string[]> errors)
        : base("One or more validation failures have occurred.")
    {
        Errors = errors;
    }
}
