// (C) Generated by Claude

namespace LinkedInOptimizer.Domain.Exceptions;

public class ResourceNotFoundException : Exception
{
    public string ResourceName { get; }
    public object Key { get; }

    public ResourceNotFoundException(string resourceName, object key)
        : base($"{resourceName} with key '{key}' was not found.")
    {
        ResourceName = resourceName;
        Key = key;
    }
}
