// (C) Generated by Claude

using LinkedInOptimizer.Application.Analyses;
using LinkedInOptimizer.Application.Common.Interfaces;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace LinkedInOptimizer.Api.Controllers;

public record StartAnalysisRequest(Guid ProfileId, Guid CvId);

[ApiController]
[Route("api/analyses")]
[Authorize]
public class AnalysisController : ControllerBase
{
    private readonly IMediator _mediator;
    private readonly ICurrentUser _currentUser;

    public AnalysisController(IMediator mediator, ICurrentUser currentUser)
    {
        _mediator = mediator;
        _currentUser = currentUser;
    }

    [HttpPost]
    public async Task<IActionResult> StartAnalysis(
        [FromBody] StartAnalysisRequest request,
        CancellationToken cancellationToken)
    {
        var result = await _mediator.Send(
            new StartAnalysisCommand(_currentUser.UserId, request.ProfileId, request.CvId),
            cancellationToken);

        return Ok(result);
    }

    [HttpGet("{id:guid}")]
    public async Task<IActionResult> GetAnalysis(Guid id, CancellationToken cancellationToken)
    {
        var result = await _mediator.Send(
            new GetAnalysisQuery(_currentUser.UserId, id),
            cancellationToken);

        return Ok(result);
    }
}
