// (C) Generated by Claude

using LinkedInOptimizer.Application.Common.Interfaces;
using LinkedInOptimizer.Application.Cvs;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace LinkedInOptimizer.Api.Controllers;

[ApiController]
[Route("api/cvs")]
[Authorize]
public class CvController : ControllerBase
{
    private readonly IMediator _mediator;
    private readonly ICurrentUser _currentUser;

    public CvController(IMediator mediator, ICurrentUser currentUser)
    {
        _mediator = mediator;
        _currentUser = currentUser;
    }

    [HttpPost]
    public async Task<IActionResult> UploadCv(IFormFile file, CancellationToken cancellationToken)
    {
        if (file is null)
            return BadRequest();

        var result = await _mediator.Send(
            new UploadCvCommand(
                _currentUser.UserId,
                file.OpenReadStream(),
                file.FileName,
                file.ContentType,
                file.Length),
            cancellationToken);

        return Ok(result);
    }

    [HttpGet("{id:guid}")]
    public async Task<IActionResult> GetCv(Guid id, CancellationToken cancellationToken)
    {
        var result = await _mediator.Send(
            new GetCvQuery(_currentUser.UserId, id),
            cancellationToken);

        return Ok(result);
    }
}
