// (C) Generated by Claude

using LinkedInOptimizer.Application.Common.Interfaces;
using LinkedInOptimizer.Application.Payments;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace LinkedInOptimizer.Api.Controllers;

public record VerifyPaymentRequest(string Reference);

[ApiController]
[Route("api/payments")]
[Authorize]
public class PaymentsController : ControllerBase
{
    private readonly IMediator _mediator;
    private readonly ICurrentUser _currentUser;

    public PaymentsController(IMediator mediator, ICurrentUser currentUser)
    {
        _mediator = mediator;
        _currentUser = currentUser;
    }

    [HttpPost("initialize")]
    public async Task<IActionResult> Initialize(CancellationToken cancellationToken)
    {
        var result = await _mediator.Send(
            new InitializePaymentCommand(_currentUser.UserId, _currentUser.Email),
            cancellationToken);

        return Ok(result);
    }

    [HttpPost("verify")]
    public async Task<IActionResult> Verify([FromBody] VerifyPaymentRequest request, CancellationToken cancellationToken)
    {
        await _mediator.Send(
            new VerifyPaymentCommand(_currentUser.UserId, request.Reference),
            cancellationToken);

        return Ok();
    }
}
