// (C) Generated by Claude

using LinkedInOptimizer.Application.Common.Interfaces;
using LinkedInOptimizer.Application.Profiles;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace LinkedInOptimizer.Api.Controllers;

public record IngestProfileRequest(string LinkedInUrl, string RawText);

[ApiController]
[Route("api/profiles")]
[Authorize]
public class ProfileController : ControllerBase
{
    private readonly IMediator _mediator;
    private readonly ICurrentUser _currentUser;

    public ProfileController(IMediator mediator, ICurrentUser currentUser)
    {
        _mediator = mediator;
        _currentUser = currentUser;
    }

    [HttpPost]
    public async Task<IActionResult> IngestProfile(
        [FromBody] IngestProfileRequest request,
        CancellationToken cancellationToken)
    {
        var result = await _mediator.Send(
            new IngestProfileCommand(_currentUser.UserId, request.LinkedInUrl, request.RawText),
            cancellationToken);

        return Ok(result);
    }
}
