// (C) Generated by Claude

using LinkedInOptimizer.Application.Payments;
using LinkedInOptimizer.Domain.Exceptions;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;

namespace LinkedInOptimizer.Api.Controllers;

[ApiController]
[Route("api/webhooks")]
[AllowAnonymous]
public class WebhooksController : ControllerBase
{
    private readonly IMediator _mediator;

    public WebhooksController(IMediator mediator)
    {
        _mediator = mediator;
    }

    [HttpPost("paystack")]
    [Consumes("application/json")]
    public async Task<IActionResult> HandlePaystack()
    {
        using var reader = new StreamReader(Request.Body);
        var rawBody = await reader.ReadToEndAsync();

        var signature = Request.Headers["x-paystack-signature"].ToString();

        using var doc = JsonDocument.Parse(rawBody);
        var eventType = doc.RootElement.GetProperty("event").GetString() ?? string.Empty;
        var reference = doc.RootElement.GetProperty("data").GetProperty("reference").GetString() ?? string.Empty;

        try
        {
            await _mediator.Send(new HandlePaystackWebhookCommand(rawBody, signature, eventType, reference));
        }
        catch (BusinessRuleViolationException)
        {
            return BadRequest();
        }

        return Ok();
    }
}
