// (C) Generated by Claude

using LinkedInOptimizer.Domain.Entities;
using LinkedInOptimizer.Domain.ValueObjects;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace LinkedInOptimizer.Infrastructure.Persistence.Configurations;

public class AnalysisConfiguration : IEntityTypeConfiguration<Analysis>
{
    public void Configure(EntityTypeBuilder<Analysis> builder)
    {
        builder.ToTable("analyses");
        builder.HasKey(a => a.Id);
        builder.Property(a => a.Id).HasColumnName("id");

        builder.Property(a => a.UserId).HasColumnName("user_id").IsRequired();
        builder.HasOne<User>()
            .WithMany()
            .HasForeignKey(nameof(Analysis.UserId))
            .OnDelete(DeleteBehavior.Cascade);

        builder.Property(a => a.ProfileId).HasColumnName("profile_id").IsRequired();
        builder.HasOne<Profile>()
            .WithMany()
            .HasForeignKey(nameof(Analysis.ProfileId))
            .OnDelete(DeleteBehavior.Cascade);

        builder.Property(a => a.CvId).HasColumnName("cv_id").IsRequired();
        builder.HasOne<Cv>()
            .WithMany()
            .HasForeignKey(nameof(Analysis.CvId))
            .OnDelete(DeleteBehavior.Cascade);

        builder.Property(a => a.Score)
            .HasColumnName("score")
            .IsRequired()
            .HasConversion(
                s => s.Value,
                v => ProfileScore.From(v));

        builder.Property(a => a.ProblemsJson)
            .HasColumnName("problems_json")
            .HasColumnType("jsonb")
            .IsRequired();

        builder.Property(a => a.Status)
            .HasColumnName("status")
            .IsRequired()
            .HasConversion(
                s => s.ToString(),
                v => v == "generating" ? AnalysisStatus.Generating
                   : v == "complete"   ? AnalysisStatus.Complete
                   : v == "failed"     ? AnalysisStatus.Failed
                   : AnalysisStatus.Scored);

        builder.Property(a => a.CreatedAt)
            .HasColumnName("created_at")
            .IsRequired();

        builder.HasIndex(a => new { a.UserId, a.CreatedAt })
            .HasDatabaseName("idx_analyses_user_created");
    }
}
