// (C) Generated by Claude

using LinkedInOptimizer.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace LinkedInOptimizer.Infrastructure.Persistence.Configurations;

public class CvConfiguration : IEntityTypeConfiguration<Cv>
{
    public void Configure(EntityTypeBuilder<Cv> builder)
    {
        builder.ToTable("cvs");
        builder.HasKey(c => c.Id);
        builder.Property(c => c.Id).HasColumnName("id");

        builder.Property(c => c.UserId).HasColumnName("user_id").IsRequired();
        builder.HasOne<User>()
            .WithOne()
            .HasForeignKey<Cv>(c => c.UserId)
            .OnDelete(DeleteBehavior.Cascade);
        builder.HasIndex(c => c.UserId).IsUnique();

        builder.Property(c => c.CloudinaryPublicId)
            .HasColumnName("cloudinary_public_id")
            .IsRequired();

        builder.Property(c => c.OriginalFilename)
            .HasColumnName("original_filename")
            .IsRequired();

        builder.Property(c => c.ParsedJson)
            .HasColumnName("parsed_json")
            .HasColumnType("jsonb")
            .IsRequired();

        builder.Property(c => c.UploadedAt)
            .HasColumnName("uploaded_at")
            .IsRequired();
    }
}
