// (C) Generated by Claude

using LinkedInOptimizer.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace LinkedInOptimizer.Infrastructure.Persistence.Configurations;

public class PaymentConfiguration : IEntityTypeConfiguration<Payment>
{
    public void Configure(EntityTypeBuilder<Payment> builder)
    {
        builder.ToTable("payments");
        builder.HasKey(p => p.Id);
        builder.Property(p => p.Id).HasColumnName("id");

        builder.Property(p => p.UserId).HasColumnName("user_id").IsRequired();
        builder.HasOne<User>()
            .WithMany()
            .HasForeignKey(nameof(Payment.UserId))
            .OnDelete(DeleteBehavior.Cascade);

        builder.Property(p => p.PaystackReference)
            .HasColumnName("paystack_reference")
            .IsRequired();
        builder.HasIndex(p => p.PaystackReference).IsUnique();

        builder.Property(p => p.Amount)
            .HasColumnName("amount")
            .IsRequired();

        builder.Property(p => p.Currency)
            .HasColumnName("currency")
            .HasColumnType("char(3)")
            .IsRequired();

        builder.Property(p => p.Status)
            .HasColumnName("status")
            .IsRequired();

        builder.Property(p => p.PaidAt)
            .HasColumnName("paid_at");
    }
}
