// (C) Generated by Claude

using LinkedInOptimizer.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace LinkedInOptimizer.Infrastructure.Persistence.Configurations;

public class ProfileConfiguration : IEntityTypeConfiguration<Profile>
{
    public void Configure(EntityTypeBuilder<Profile> builder)
    {
        builder.ToTable("profiles");
        builder.HasKey(p => p.Id);
        builder.Property(p => p.Id).HasColumnName("id");

        builder.Property(p => p.UserId).HasColumnName("user_id").IsRequired();
        builder.HasOne<User>()
            .WithMany()
            .HasForeignKey(nameof(Profile.UserId))
            .OnDelete(DeleteBehavior.Cascade);

        builder.Property(p => p.LinkedInUrl)
            .HasColumnName("linkedin_url")
            .IsRequired();

        builder.Property(p => p.RawText)
            .HasColumnName("raw_text")
            .IsRequired();

        builder.Property(p => p.ParsedJson)
            .HasColumnName("parsed_json")
            .HasColumnType("jsonb")
            .IsRequired();

        builder.Property(p => p.IngestedAt)
            .HasColumnName("ingested_at")
            .IsRequired();
    }
}
