// (C) Generated by Claude

using LinkedInOptimizer.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace LinkedInOptimizer.Infrastructure.Persistence.Configurations;

public class RewriteConfiguration : IEntityTypeConfiguration<Rewrite>
{
    public void Configure(EntityTypeBuilder<Rewrite> builder)
    {
        builder.ToTable("rewrites");
        builder.HasKey(r => r.Id);
        builder.Property(r => r.Id).HasColumnName("id");

        builder.Property(r => r.AnalysisId).HasColumnName("analysis_id").IsRequired();
        builder.HasOne<Analysis>()
            .WithOne()
            .HasForeignKey<Rewrite>(r => r.AnalysisId)
            .OnDelete(DeleteBehavior.Cascade);
        builder.HasIndex(r => r.AnalysisId).IsUnique();

        builder.Property(r => r.HeadlinesJson)
            .HasColumnName("headlines_json")
            .HasColumnType("jsonb")
            .IsRequired();

        builder.Property(r => r.AboutJson)
            .HasColumnName("about_json")
            .HasColumnType("jsonb")
            .IsRequired();

        builder.Property(r => r.ExperienceJson)
            .HasColumnName("experience_json")
            .HasColumnType("jsonb")
            .IsRequired();

        builder.Property(r => r.SkillsJson)
            .HasColumnName("skills_json")
            .HasColumnType("jsonb")
            .IsRequired();

        builder.Property(r => r.BannerJson)
            .HasColumnName("banner_json")
            .HasColumnType("jsonb")
            .IsRequired();

        builder.Property(r => r.TipsJson)
            .HasColumnName("tips_json")
            .HasColumnType("jsonb")
            .IsRequired();

        builder.Property(r => r.GeneratedAt)
            .HasColumnName("generated_at")
            .IsRequired();
    }
}
