// (C) Generated by Claude

using LinkedInOptimizer.Domain.Entities;
using LinkedInOptimizer.Domain.ValueObjects;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace LinkedInOptimizer.Infrastructure.Persistence.Configurations;

public class UserConfiguration : IEntityTypeConfiguration<User>
{
    public void Configure(EntityTypeBuilder<User> builder)
    {
        builder.ToTable("users");
        builder.HasKey(u => u.Id);
        builder.Property(u => u.Id).HasColumnName("id");
        builder.Property(u => u.Email).HasColumnName("email").IsRequired();
        builder.HasIndex(u => u.Email).IsUnique();
        builder.Property(u => u.PasswordHash).HasColumnName("password_hash").IsRequired();
        builder.Property(u => u.CreatedAt).HasColumnName("created_at").IsRequired();

        builder.Property(u => u.Tier)
            .HasColumnName("tier")
            .IsRequired()
            .HasDefaultValue(Tier.Free)
            .HasConversion(
                tier => tier.ToString(),
                value => value == "premium" ? Tier.Premium : Tier.Free);
    }
}
