// <auto-generated />
using System;
using LinkedInOptimizer.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LinkedInOptimizer.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LinkedInOptimizer.Domain.Entities.Analysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CvId")
                        .HasColumnType("uuid")
                        .HasColumnName("cv_id");

                    b.Property<string>("ProblemsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("problems_json");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CvId");

                    b.HasIndex("ProfileId");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("idx_analyses_user_created");

                    b.ToTable("analyses", (string)null);
                });

            modelBuilder.Entity("LinkedInOptimizer.Domain.Entities.Cv", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CloudinaryPublicId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cloudinary_public_id");

                    b.Property<string>("OriginalFilename")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_filename");

                    b.Property<string>("ParsedJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("parsed_json");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("cvs", (string)null);
                });

            modelBuilder.Entity("LinkedInOptimizer.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Amount")
                        .HasColumnType("integer")
                        .HasColumnName("amount");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<string>("PaystackReference")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("paystack_reference");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("PaystackReference")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("LinkedInOptimizer.Domain.Entities.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("IngestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ingested_at");

                    b.Property<string>("LinkedInUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("linkedin_url");

                    b.Property<string>("ParsedJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("parsed_json");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("LinkedInOptimizer.Domain.Entities.Rewrite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AboutJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("about_json");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uuid")
                        .HasColumnName("analysis_id");

                    b.Property<string>("BannerJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("banner_json");

                    b.Property<string>("ExperienceJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("experience_json");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<string>("HeadlinesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("headlines_json");

                    b.Property<string>("SkillsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("skills_json");

                    b.Property<string>("TipsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("tips_json");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId")
                        .IsUnique();

                    b.ToTable("rewrites", (string)null);
                });

            modelBuilder.Entity("LinkedInOptimizer.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("free")
                        .HasColumnName("tier");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("LinkedInOptimizer.Domain.Entities.Analysis", b =>
                {
                    b.HasOne("LinkedInOptimizer.Domain.Entities.Cv", null)
                        .WithMany()
                        .HasForeignKey("CvId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LinkedInOptimizer.Domain.Entities.Profile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LinkedInOptimizer.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LinkedInOptimizer.Domain.Entities.Cv", b =>
                {
                    b.HasOne("LinkedInOptimizer.Domain.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("LinkedInOptimizer.Domain.Entities.Cv", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LinkedInOptimizer.Domain.Entities.Payment", b =>
                {
                    b.HasOne("LinkedInOptimizer.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LinkedInOptimizer.Domain.Entities.Profile", b =>
                {
                    b.HasOne("LinkedInOptimizer.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LinkedInOptimizer.Domain.Entities.Rewrite", b =>
                {
                    b.HasOne("LinkedInOptimizer.Domain.Entities.Analysis", null)
                        .WithOne()
                        .HasForeignKey("LinkedInOptimizer.Domain.Entities.Rewrite", "AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
