// (C) Generated by Claude

using LinkedInOptimizer.Domain.Entities;
using Microsoft.EntityFrameworkCore;

namespace LinkedInOptimizer.Infrastructure.Persistence;

public class AppDbContext : DbContext
{
    public AppDbContext(DbContextOptions<AppDbContext> options) : base(options) { }

    public DbSet<User> Users => Set<User>();
    public DbSet<Cv> Cvs => Set<Cv>();
    public DbSet<Profile> Profiles => Set<Profile>();
    public DbSet<Analysis> Analyses => Set<Analysis>();
    public DbSet<Rewrite> Rewrites => Set<Rewrite>();
    public DbSet<Payment> Payments => Set<Payment>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfigurationsFromAssembly(typeof(AppDbContext).Assembly);
        base.OnModelCreating(modelBuilder);
    }
}
