// (C) Generated by Claude

using LinkedInOptimizer.Domain.Common;
using LinkedInOptimizer.Domain.Exceptions;
using LinkedInOptimizer.Domain.ValueObjects;

namespace LinkedInOptimizer.Domain.Entities;

public class Analysis : Entity
{
    public Guid UserId { get; private set; }
    public Guid ProfileId { get; private set; }
    public Guid CvId { get; private set; }
    public ProfileScore Score { get; private set; } = null!;
    public string ProblemsJson { get; private set; } = null!;
    public AnalysisStatus Status { get; private set; } = null!;
    public DateTime CreatedAt { get; private set; }

    private Analysis() { }

    public static Analysis Create(Guid userId, Guid profileId, Guid cvId,
                                  ProfileScore score, string problemsJson)
        => new Analysis
        {
            UserId = userId,
            ProfileId = profileId,
            CvId = cvId,
            Score = score,
            ProblemsJson = problemsJson,
            Status = AnalysisStatus.Scored,
            CreatedAt = DateTime.UtcNow
        };

    public void MarkGenerating()
    {
        if (Status == AnalysisStatus.Generating || Status == AnalysisStatus.Complete)
            throw new BusinessRuleViolationException(
                $"Cannot transition to Generating from {Status}.");
        Status = AnalysisStatus.Generating;
    }

    public void MarkComplete()
    {
        if (Status != AnalysisStatus.Generating)
            throw new BusinessRuleViolationException(
                "MarkComplete requires Status = Generating.");
        Status = AnalysisStatus.Complete;
    }

    public void MarkFailed()
    {
        Status = AnalysisStatus.Failed;
    }
}
