// (C) Generated by Claude

using LinkedInOptimizer.Domain.Common;
using LinkedInOptimizer.Domain.Exceptions;

namespace LinkedInOptimizer.Domain.Entities;

public class Cv : Entity
{
    public Guid UserId { get; private set; }
    public string CloudinaryPublicId { get; private set; } = null!;
    public string OriginalFilename { get; private set; } = null!;
    public string ParsedJson { get; private set; } = null!;
    public DateTime UploadedAt { get; private set; }

    private Cv() { }

    public static Cv Create(Guid userId, string cloudinaryPublicId,
                            string originalFilename, string parsedJson)
    {
        if (string.IsNullOrWhiteSpace(cloudinaryPublicId))
            throw new BusinessRuleViolationException("CloudinaryPublicId is required.");

        return new Cv
        {
            UserId = userId,
            CloudinaryPublicId = cloudinaryPublicId,
            OriginalFilename = originalFilename,
            ParsedJson = parsedJson,
            UploadedAt = DateTime.UtcNow
        };
    }
}
