// (C) Generated by Claude

using LinkedInOptimizer.Domain.Common;

namespace LinkedInOptimizer.Domain.Entities;

public class Payment : Entity
{
    public Guid UserId { get; private set; }
    public string PaystackReference { get; private set; } = null!;
    public int Amount { get; private set; }
    public string Currency { get; private set; } = null!;
    public string Status { get; private set; } = null!;
    public DateTime? PaidAt { get; private set; }

    private Payment() { }

    public static Payment Create(Guid userId, string paystackReference,
                                 int amount, string currency)
        => new Payment
        {
            UserId = userId,
            PaystackReference = paystackReference,
            Amount = amount,
            Currency = currency,
            Status = "pending"
        };

    public void MarkSuccess()
    {
        Status = "success";
        PaidAt = DateTime.UtcNow;
    }
}
