// (C) Generated by Claude

using LinkedInOptimizer.Domain.Common;
using LinkedInOptimizer.Domain.Exceptions;

namespace LinkedInOptimizer.Domain.Entities;

public class Profile : Entity
{
    public Guid UserId { get; private set; }
    public string LinkedInUrl { get; private set; } = null!;
    public string RawText { get; private set; } = null!;
    public string ParsedJson { get; private set; } = null!;
    public DateTime IngestedAt { get; private set; }

    private Profile() { }

    public static Profile Create(Guid userId, string linkedInUrl,
                                 string rawText, string parsedJson)
    {
        if (string.IsNullOrWhiteSpace(rawText))
            throw new BusinessRuleViolationException("RawText is required.");

        return new Profile
        {
            UserId = userId,
            LinkedInUrl = linkedInUrl,
            RawText = rawText,
            ParsedJson = parsedJson,
            IngestedAt = DateTime.UtcNow
        };
    }
}
