// (C) Generated by Claude

using LinkedInOptimizer.Domain.Common;

namespace LinkedInOptimizer.Domain.Entities;

public class Rewrite : Entity
{
    public Guid AnalysisId { get; private set; }
    public string HeadlinesJson { get; private set; } = null!;
    public string AboutJson { get; private set; } = null!;
    public string ExperienceJson { get; private set; } = null!;
    public string SkillsJson { get; private set; } = null!;
    public string BannerJson { get; private set; } = null!;
    public string TipsJson { get; private set; } = null!;
    public DateTime GeneratedAt { get; private set; }

    private Rewrite() { }

    public static Rewrite Create(Guid analysisId, string headlinesJson,
        string aboutJson, string experienceJson, string skillsJson,
        string bannerJson, string tipsJson)
        => new Rewrite
        {
            AnalysisId = analysisId,
            HeadlinesJson = headlinesJson,
            AboutJson = aboutJson,
            ExperienceJson = experienceJson,
            SkillsJson = skillsJson,
            BannerJson = bannerJson,
            TipsJson = tipsJson,
            GeneratedAt = DateTime.UtcNow
        };
}
