// (C) Generated by Claude

using LinkedInOptimizer.Domain.Common;
using LinkedInOptimizer.Domain.Exceptions;
using LinkedInOptimizer.Domain.ValueObjects;

namespace LinkedInOptimizer.Domain.Entities;

public class User : Entity
{
    public string Email { get; private set; } = null!;
    public string PasswordHash { get; private set; } = null!;
    public Tier Tier { get; private set; } = null!;
    public DateTime CreatedAt { get; private set; }

    private User() { }

    public static User Create(string email, string passwordHash)
    {
        if (string.IsNullOrWhiteSpace(email))
            throw new BusinessRuleViolationException("User email is required.");
        if (string.IsNullOrWhiteSpace(passwordHash))
            throw new BusinessRuleViolationException("User password hash is required.");

        return new User
        {
            Email = email.ToLowerInvariant(),
            PasswordHash = passwordHash,
            Tier = Tier.Free,
            CreatedAt = DateTime.UtcNow
        };
    }

    public void UpgradeToPremium()
    {
        if (Tier.IsPremium)
            throw new BusinessRuleViolationException("User is already on the Premium tier.");

        Tier = Tier.Premium;
    }
}
