// (C) Generated by Claude

using System.Text.Json;
using System.Text.RegularExpressions;
using LinkedInOptimizer.Domain.ValueObjects;

namespace LinkedInOptimizer.Application.Scoring;

public class ProfileScorer
{
    // -----------------------------------------------------------------------
    // Public entry point
    // -----------------------------------------------------------------------

    public (ProfileScore Score, string[] Problems) Score(
        string profileJson, string cvJson)
    {
        var profile = ParseProfile(profileJson);
        var cv      = ParseCv(cvJson);

        var (headlineScore,  headlineProblem)  = ScoreHeadline(profile);
        var (aboutScore,     aboutProblem)     = ScoreAbout(profile);
        var (experienceScore, experienceProblem) = ScoreExperience(profile);
        var (skillsScore,    skillsProblem)    = ScoreSkills(profile, cv);

        int total = headlineScore + aboutScore + experienceScore + skillsScore;

        // Identify the 3 lowest-scoring dimensions and return their problems.
        var dimensions = new[]
        {
            (Score: headlineScore,   Problem: headlineProblem,   Name: "Headline"),
            (Score: aboutScore,      Problem: aboutProblem,      Name: "About"),
            (Score: experienceScore, Problem: experienceProblem, Name: "Experience"),
            (Score: skillsScore,     Problem: skillsProblem,     Name: "Skills"),
        };

        var problems = dimensions
            .OrderBy(d => d.Score)
            .Take(3)
            .Select(d => d.Problem)
            .ToArray();

        return (ProfileScore.From(total), problems);
    }

    // -----------------------------------------------------------------------
    // Dimension 1 — Headline quality (0–25)
    // -----------------------------------------------------------------------

    private static (int Score, string Problem) ScoreHeadline(ProfileData profile)
    {
        var headline = profile.Headline ?? string.Empty;
        int score = 0;

        // Length check: >10 chars = 10 pts
        if (headline.Length > 10)
            score += 10;

        // Professional keywords: 5 pts each, max 10 pts
        var professionalKeywords = new[]
        {
            "engineer", "developer", "manager", "lead", "senior", "specialist"
        };
        int keywordPts = 0;
        foreach (var kw in professionalKeywords)
        {
            if (headline.Contains(kw, StringComparison.OrdinalIgnoreCase))
                keywordPts += 5;
            if (keywordPts >= 10) break;
        }
        score += keywordPts;

        // Value proposition words: 5 pts
        var valueWords = new[] { "helping", "building", "driving" };
        bool hasValueProp = valueWords.Any(w =>
            headline.Contains(w, StringComparison.OrdinalIgnoreCase));
        if (hasValueProp)
            score += 5;

        // Build problem statement
        string problem;
        if (string.IsNullOrWhiteSpace(headline))
        {
            problem = "Your headline is missing. Add a headline that includes your role title and a value proposition (e.g., \"Senior Engineer | Helping teams ship faster\").";
        }
        else if (score < 10)
        {
            problem = $"Your headline \"{Truncate(headline, 60)}\" is too short or generic. Include a professional keyword (engineer, developer, manager, etc.) and a value proposition word (helping, building, driving).";
        }
        else if (keywordPts == 0)
        {
            problem = $"Your headline \"{Truncate(headline, 60)}\" lacks a professional role keyword. Add terms like \"engineer\", \"developer\", \"manager\", or \"lead\" to improve discoverability.";
        }
        else
        {
            problem = $"Your headline \"{Truncate(headline, 60)}\" could be stronger. Add a value proposition word such as \"helping\", \"building\", or \"driving\" to stand out.";
        }

        return (Math.Min(score, 25), problem);
    }

    // -----------------------------------------------------------------------
    // Dimension 2 — About section completeness (0–25)
    // -----------------------------------------------------------------------

    private static (int Score, string Problem) ScoreAbout(ProfileData profile)
    {
        var about = profile.About ?? string.Empty;
        int score = 0;

        // Length scoring
        if (about.Length > 250)
            score += 15;
        else if (about.Length > 100)
            score += 10;

        // First-person pronouns: 5 pts
        bool hasFirstPerson = Regex.IsMatch(about, @"\b(I|my|me)\b",
            RegexOptions.IgnoreCase);
        if (hasFirstPerson)
            score += 5;

        // Call-to-action or contact info: 5 pts
        bool hasCta = Regex.IsMatch(about,
            @"(reach out|contact me|connect with me|email me|feel free|let'?s talk|dm me|message me|@|linkedin\.com)",
            RegexOptions.IgnoreCase);
        if (hasCta)
            score += 5;

        // Build problem statement
        string problem;
        if (string.IsNullOrWhiteSpace(about))
        {
            problem = "Your About section is empty. Write at least 250 characters describing your background, what you do, and how to reach you.";
        }
        else if (about.Length <= 100)
        {
            problem = $"Your About section is too brief ({about.Length} characters). Expand it to over 250 characters with your story, achievements, and a call-to-action.";
        }
        else if (!hasFirstPerson)
        {
            problem = "Your About section reads in third person. Rewrite it using first-person pronouns (\"I\", \"my\", \"me\") to make it more personal and engaging.";
        }
        else if (!hasCta)
        {
            problem = "Your About section lacks a call-to-action. End with an invitation to connect, such as \"Feel free to reach out at [email]\" or \"Let's connect on LinkedIn\".";
        }
        else
        {
            problem = "Your About section could be more compelling. Ensure it covers your background, key achievements, and ends with a clear call-to-action.";
        }

        return (Math.Min(score, 25), problem);
    }

    // -----------------------------------------------------------------------
    // Dimension 3 — Experience depth (0–25)
    // -----------------------------------------------------------------------

    private static (int Score, string Problem) ScoreExperience(ProfileData profile)
    {
        var experience = profile.Experience ?? Array.Empty<ExperienceEntry>();
        int score = 0;

        // Number of roles
        if (experience.Length >= 2)
            score += 10;
        else if (experience.Length == 1)
            score += 5;

        // Average bullets per role: 2+ bullets = 10 pts
        if (experience.Length > 0)
        {
            double avgBullets = experience.Average(e =>
                e.Bullets?.Length ?? 0);
            if (avgBullets >= 2)
                score += 10;
        }

        // Presence of numbers/metrics in bullets: 5 pts
        bool hasMetrics = experience
            .SelectMany(e => e.Bullets ?? Array.Empty<string>())
            .Any(b => Regex.IsMatch(b, @"\d"));
        if (hasMetrics)
            score += 5;

        // Build problem statement
        string problem;
        if (experience.Length == 0)
        {
            problem = "Your Experience section is empty. Add at least two roles with 2+ bullet points each, including quantified achievements (e.g., \"Reduced load time by 40%\").";
        }
        else if (experience.Length == 1)
        {
            problem = $"You only have 1 role listed (\"{Truncate(experience[0].Title ?? "Unknown", 40)}\"). Add more positions to show career progression.";
        }
        else if (!hasMetrics)
        {
            problem = "Your experience bullets lack quantified achievements. Add numbers and metrics (e.g., \"Increased revenue by 20%\", \"Led a team of 8 engineers\") to make your impact concrete.";
        }
        else
        {
            double avgBullets = experience.Average(e => e.Bullets?.Length ?? 0);
            problem = $"Your experience roles average {avgBullets:F1} bullets each. Aim for at least 2 bullets per role with specific, metric-driven accomplishments.";
        }

        return (Math.Min(score, 25), problem);
    }

    // -----------------------------------------------------------------------
    // Dimension 4 — Skills coverage (0–25)
    // -----------------------------------------------------------------------

    private static (int Score, string Problem) ScoreSkills(
        ProfileData profile, CvData cv)
    {
        var skills = profile.Skills ?? Array.Empty<string>();
        int score = 0;

        // Count-based scoring
        if (skills.Length >= 10)
            score += 15;
        else if (skills.Length >= 5)
            score += 10;

        // Cross-reference with CV roles for relevance: 5 pts
        var cvRoleTitles = cv.Roles?
            .Select(r => r.Title ?? string.Empty)
            .Where(t => !string.IsNullOrWhiteSpace(t))
            .ToArray() ?? Array.Empty<string>();

        bool hasRelevantSkills = skills.Any(skill =>
            cvRoleTitles.Any(title =>
                title.Contains(skill, StringComparison.OrdinalIgnoreCase) ||
                skill.Contains(title, StringComparison.OrdinalIgnoreCase)));

        // Fallback: if CV has no roles, award relevance points when skills exist
        if (cvRoleTitles.Length == 0 && skills.Length > 0)
            hasRelevantSkills = true;

        if (hasRelevantSkills)
            score += 5;

        // Technical skills presence: 5 pts
        var technicalKeywords = new[]
        {
            "python", "java", "javascript", "typescript", "c#", "c++", "go",
            "rust", "sql", "nosql", "aws", "azure", "gcp", "docker",
            "kubernetes", "react", "angular", "vue", "node", ".net",
            "machine learning", "ml", "ai", "data", "api", "rest", "graphql",
            "git", "ci/cd", "devops", "linux", "agile", "scrum"
        };
        bool hasTechnicalSkill = skills.Any(skill =>
            technicalKeywords.Any(kw =>
                skill.Contains(kw, StringComparison.OrdinalIgnoreCase)));
        if (hasTechnicalSkill)
            score += 5;

        // Build problem statement
        string problem;
        if (skills.Length == 0)
        {
            problem = "Your Skills section is empty. Add at least 10 skills, including technical tools and technologies relevant to your roles.";
        }
        else if (skills.Length < 5)
        {
            problem = $"You only have {skills.Length} skill(s) listed. Add at least 10 skills — including technical skills like programming languages, frameworks, and tools — to improve profile visibility.";
        }
        else if (!hasTechnicalSkill)
        {
            problem = $"Your {skills.Length} listed skills lack technical keywords. Add specific technologies (e.g., Python, AWS, Docker, React) to attract recruiters searching for technical talent.";
        }
        else
        {
            problem = $"You have {skills.Length} skills listed. Aim for 10+ skills and ensure they align with the technologies mentioned in your experience bullets.";
        }

        return (Math.Min(score, 25), problem);
    }

    // -----------------------------------------------------------------------
    // JSON parsing helpers
    // -----------------------------------------------------------------------

    private static ProfileData ParseProfile(string profileJson)
    {
        if (string.IsNullOrWhiteSpace(profileJson))
            return new ProfileData();

        try
        {
            return JsonSerializer.Deserialize<ProfileData>(profileJson,
                JsonOptions) ?? new ProfileData();
        }
        catch (JsonException)
        {
            return new ProfileData();
        }
    }

    private static CvData ParseCv(string cvJson)
    {
        if (string.IsNullOrWhiteSpace(cvJson))
            return new CvData();

        try
        {
            return JsonSerializer.Deserialize<CvData>(cvJson,
                JsonOptions) ?? new CvData();
        }
        catch (JsonException)
        {
            return new CvData();
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        PropertyNameCaseInsensitive = true,
    };

    // -----------------------------------------------------------------------
    // Utility
    // -----------------------------------------------------------------------

    private static string Truncate(string value, int maxLength)
        => value.Length <= maxLength ? value : value[..maxLength] + "…";

    // -----------------------------------------------------------------------
    // Internal data models (deserialization targets)
    // -----------------------------------------------------------------------

    private sealed class ProfileData
    {
        public string? Headline   { get; set; }
        public string? About      { get; set; }
        public ExperienceEntry[]? Experience { get; set; }
        public string[]?          Skills     { get; set; }
    }

    private sealed class ExperienceEntry
    {
        public string?   Title   { get; set; }
        public string?   Company { get; set; }
        public string[]? Bullets { get; set; }
    }

    private sealed class CvData
    {
        public CvRole[]? Roles { get; set; }
    }

    private sealed class CvRole
    {
        public string?   Title   { get; set; }
        public string?   Company { get; set; }
        public string[]? Bullets { get; set; }
    }
}
