// (C) Generated by Claude

using System.Net.Http.Json;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using LinkedInOptimizer.Application.Common.Dtos;
using LinkedInOptimizer.Application.Common.Interfaces;
using LinkedInOptimizer.Infrastructure.Options;
using Microsoft.Extensions.Configuration;

namespace LinkedInOptimizer.Infrastructure.Payments;

public sealed class PaystackClient : IPaystackClient
{
    private const string BaseUrl = "https://api.paystack.co";

    private readonly IHttpClientFactory _httpClientFactory;
    private readonly PaystackOptions _options;

    public PaystackClient(IHttpClientFactory httpClientFactory, IConfiguration configuration)
    {
        _httpClientFactory = httpClientFactory;
        _options = configuration.GetSection("Paystack").Get<PaystackOptions>() ?? new PaystackOptions();
    }

    public async Task<PaystackInitResult> InitializeTransactionAsync(
        string email,
        int amountKobo,
        CancellationToken ct)
    {
        using var client = _httpClientFactory.CreateClient();
        client.DefaultRequestHeaders.Authorization =
            new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", _options.SecretKey);

        var payload = new { email, amount = amountKobo };
        var response = await client.PostAsJsonAsync($"{BaseUrl}/transaction/initialize", payload, ct);

        if (!response.IsSuccessStatusCode)
            throw new InvalidOperationException(
                $"Paystack initialize transaction failed with status {(int)response.StatusCode}.");

        using var doc = await JsonDocument.ParseAsync(
            await response.Content.ReadAsStreamAsync(ct), cancellationToken: ct);

        var root = doc.RootElement;

        if (!root.TryGetProperty("status", out var statusProp) || !statusProp.GetBoolean())
            throw new InvalidOperationException(
                "Paystack initialize transaction returned status=false.");

        var data = root.GetProperty("data");
        var authorizationUrl = data.GetProperty("authorization_url").GetString()
            ?? throw new InvalidOperationException("Missing authorization_url in Paystack response.");
        var reference = data.GetProperty("reference").GetString()
            ?? throw new InvalidOperationException("Missing reference in Paystack response.");

        return new PaystackInitResult(authorizationUrl, reference);
    }

    public async Task<PaystackVerifyResult> VerifyTransactionAsync(
        string reference,
        CancellationToken ct)
    {
        using var client = _httpClientFactory.CreateClient();
        client.DefaultRequestHeaders.Authorization =
            new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", _options.SecretKey);

        var response = await client.GetAsync($"{BaseUrl}/transaction/verify/{reference}", ct);

        if (!response.IsSuccessStatusCode)
            throw new InvalidOperationException(
                $"Paystack verify transaction failed with status {(int)response.StatusCode}.");

        using var doc = await JsonDocument.ParseAsync(
            await response.Content.ReadAsStreamAsync(ct), cancellationToken: ct);

        var data = doc.RootElement.GetProperty("data");
        var status = data.GetProperty("status").GetString()
            ?? throw new InvalidOperationException("Missing status in Paystack verify response.");
        var amount = data.GetProperty("amount").GetInt32();
        var currency = data.GetProperty("currency").GetString()
            ?? throw new InvalidOperationException("Missing currency in Paystack verify response.");

        return new PaystackVerifyResult(status, amount, currency);
    }

    public bool VerifyWebhookSignature(string rawBody, string paystackSignatureHeader)
    {
        var keyBytes = Encoding.UTF8.GetBytes(_options.SecretKey);
        var bodyBytes = Encoding.UTF8.GetBytes(rawBody);

        using var hmac = new HMACSHA512(keyBytes);
        var hashBytes = hmac.ComputeHash(bodyBytes);
        var computedHash = Convert.ToHexString(hashBytes).ToLowerInvariant();

        var computedBytes = Encoding.UTF8.GetBytes(computedHash);
        var signatureBytes = Encoding.UTF8.GetBytes(paystackSignatureHeader);

        if (computedBytes.Length != signatureBytes.Length)
            return false;

        return CryptographicOperations.FixedTimeEquals(computedBytes, signatureBytes);
    }
}
