// (C) Generated by Claude

using LinkedInOptimizer.Application.Common.Dtos;
using LinkedInOptimizer.Application.Common.Interfaces;
using LinkedInOptimizer.Domain.Exceptions;
using MediatR;

namespace LinkedInOptimizer.Application.Cvs;

public record GetCvQuery(Guid UserId, Guid CvId) : IRequest<CvDto>;

public class GetCvQueryHandler : IRequestHandler<GetCvQuery, CvDto>
{
    private readonly ICvRepository _cvRepository;

    public GetCvQueryHandler(ICvRepository cvRepository)
    {
        _cvRepository = cvRepository;
    }

    public async Task<CvDto> Handle(GetCvQuery query, CancellationToken ct)
    {
        var cv = await _cvRepository.GetByIdAsync(query.CvId, ct);

        if (cv is null || cv.UserId != query.UserId)
            throw new ResourceNotFoundException("Cv", query.CvId);

        return new CvDto(cv.Id, cv.OriginalFilename, cv.UploadedAt);
    }
}
