// (C) Generated by Claude

using FluentValidation;

namespace LinkedInOptimizer.Application.Cvs;

public class UploadCvCommandValidator : AbstractValidator<UploadCvCommand>
{
    public UploadCvCommandValidator()
    {
        RuleFor(x => x.FileStream)
            .Must(s => s != null)
            .WithMessage("File stream is required.");

        RuleFor(x => x.FileName)
            .NotEmpty();

        RuleFor(x => x.UserId)
            .NotEqual(Guid.Empty);
    }
}
