// (C) Generated by Claude

using LinkedInOptimizer.Application.Common.Dtos;
using LinkedInOptimizer.Application.Common.Interfaces;
using LinkedInOptimizer.Domain.Entities;
using LinkedInOptimizer.Domain.Exceptions;
using MediatR;
using Microsoft.Extensions.DependencyInjection;

namespace LinkedInOptimizer.Application.Cvs;

public record UploadCvCommand(
    Guid UserId,
    Stream FileStream,
    string FileName,
    string MimeType,
    long FileSizeBytes) : IRequest<CvDto>;

public class UploadCvCommandHandler : IRequestHandler<UploadCvCommand, CvDto>
{
    private static readonly HashSet<string> AllowedMimeTypes = new(StringComparer.OrdinalIgnoreCase)
    {
        "application/pdf",
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    };

    private const long MaxFileSizeBytes = 10L * 1024 * 1024; // 10 MB

    private readonly ICvParser _pdfParser;
    private readonly ICvParser _docxParser;
    private readonly ICloudinaryClient _cloudinaryClient;
    private readonly ICvRepository _cvRepository;
    private readonly IUnitOfWork _unitOfWork;

    public UploadCvCommandHandler(
        [FromKeyedServices("pdf")] ICvParser pdfParser,
        [FromKeyedServices("docx")] ICvParser docxParser,
        ICloudinaryClient cloudinaryClient,
        ICvRepository cvRepository,
        IUnitOfWork unitOfWork)
    {
        _pdfParser = pdfParser;
        _docxParser = docxParser;
        _cloudinaryClient = cloudinaryClient;
        _cvRepository = cvRepository;
        _unitOfWork = unitOfWork;
    }

    public async Task<CvDto> Handle(UploadCvCommand command, CancellationToken cancellationToken)
    {
        // 1. Validate MIME type
        if (!AllowedMimeTypes.Contains(command.MimeType))
            throw new BusinessRuleViolationException("Only PDF and DOCX files are accepted.");

        // 2. Validate file size
        if (command.FileSizeBytes > MaxFileSizeBytes)
            throw new BusinessRuleViolationException("CV file must not exceed 10 MB.");

        // 3. Read entire stream into memory once
        using var memoryStream = new MemoryStream();
        await command.FileStream.CopyToAsync(memoryStream, cancellationToken);
        memoryStream.Position = 0;

        // 4. Select parser by MIME type
        var parser = command.MimeType.Equals("application/pdf", StringComparison.OrdinalIgnoreCase)
            ? _pdfParser
            : _docxParser;

        // 5. Parse the CV file
        var parsedJson = await parser.ParseAsync(memoryStream, cancellationToken);

        // 6. Reset stream and upload to Cloudinary
        memoryStream.Position = 0;
        var publicId = await _cloudinaryClient.UploadRawAsync(memoryStream, command.FileName, cancellationToken);

        // 7. Remove existing CV for this user if present
        var existing = await _cvRepository.GetByUserIdAsync(command.UserId, cancellationToken);
        if (existing is not null)
        {
            await _cloudinaryClient.DeleteAsync(existing.CloudinaryPublicId, cancellationToken);
            await _cvRepository.RemoveAsync(existing, cancellationToken);
        }

        // 8. Create new CV entity
        var cv = Cv.Create(command.UserId, publicId, command.FileName, parsedJson);

        // 9. Persist
        await _cvRepository.AddAsync(cv, cancellationToken);

        // 10. Save changes
        await _unitOfWork.SaveChangesAsync(cancellationToken);

        // 11. Return DTO
        return new CvDto(cv.Id, cv.OriginalFilename, cv.UploadedAt);
    }
}
