// (C) Generated by Claude
namespace LinkedInOptimizer.Application.Common.Options;

public record AnthropicOptions
{
    public string ApiKey { get; init; } = string.Empty;
    public string Model { get; init; } = "claude-sonnet-4-5";
}
