// (C) Generated by Claude

using LinkedInOptimizer.Domain.Entities;

namespace LinkedInOptimizer.Application.Common.Interfaces;

public interface IAnalysisRepository
{
    Task AddAsync(Analysis analysis, CancellationToken ct);
    Task<Analysis?> GetByIdAsync(Guid id, CancellationToken ct);
}
