// (C) Generated by Claude

namespace LinkedInOptimizer.Application.Common.Interfaces;

public interface IClaudeClient
{
    Task<string> GenerateHeadlinesAsync(string profileJson, string cvJson, CancellationToken ct);
    Task<string> GenerateAboutAsync(string profileJson, string cvJson, CancellationToken ct);
    Task<string> GenerateExperienceAsync(string profileJson, string cvJson, CancellationToken ct);
    Task<string> GenerateAddonsAsync(string profileJson, string cvJson, CancellationToken ct);
}
