// (C) Generated by Claude

namespace LinkedInOptimizer.Application.Common.Interfaces;

public interface ICloudinaryClient
{
    Task<string> UploadRawAsync(Stream fileStream, string filename, CancellationToken ct);
    Task DeleteAsync(string publicId, CancellationToken ct);
}
