// (C) Generated by Claude

using LinkedInOptimizer.Domain.ValueObjects;

namespace LinkedInOptimizer.Application.Common.Interfaces;

public interface ICurrentUser
{
    Guid UserId { get; }
    string Email { get; }
    Tier Tier { get; }
}
