// (C) Generated by Claude

using LinkedInOptimizer.Domain.Entities;

namespace LinkedInOptimizer.Application.Common.Interfaces;

public interface ICvRepository
{
    Task<Cv?> GetByIdAsync(Guid id, CancellationToken ct = default);
    Task<Cv?> GetByUserIdAsync(Guid userId, CancellationToken ct);
    Task AddAsync(Cv cv, CancellationToken ct);
    Task RemoveAsync(Cv cv, CancellationToken ct);
}
