// (C) Generated by Claude

using System.Security.Claims;
using LinkedInOptimizer.Domain.Entities;

namespace LinkedInOptimizer.Application.Common.Interfaces;

public interface IJwtTokenService
{
    string GenerateAccessToken(User user);
    string GenerateRefreshToken();
    ClaimsPrincipal? ValidateRefreshToken(string token);
}
