// (C) Generated by Claude

namespace LinkedInOptimizer.Application.Common.Interfaces;

public interface IPasswordHasher
{
    string Hash(string password);
    bool Verify(string password, string hash);
}
