// (C) Generated by Claude

using LinkedInOptimizer.Application.Common.Dtos;

namespace LinkedInOptimizer.Application.Common.Interfaces;

public interface IPaystackClient
{
    Task<PaystackInitResult> InitializeTransactionAsync(string email, int amountKobo, CancellationToken ct);
    Task<PaystackVerifyResult> VerifyTransactionAsync(string reference, CancellationToken ct);
    bool VerifyWebhookSignature(string rawBody, string paystackSignatureHeader);
}
