// (C) Generated by Claude

using LinkedInOptimizer.Domain.Entities;

namespace LinkedInOptimizer.Application.Common.Interfaces;

public interface IPaymentRepository
{
    Task AddAsync(Payment payment, CancellationToken ct);
    Task<Payment?> GetByReferenceAsync(string reference, CancellationToken ct);
}
