// (C) Generated by Claude

using LinkedInOptimizer.Domain.Entities;

namespace LinkedInOptimizer.Application.Common.Interfaces;

public interface IProfileRepository
{
    Task AddAsync(Profile profile, CancellationToken ct);
    Task<Profile?> GetByIdAsync(Guid id, CancellationToken ct);
}
