// (C) Generated by Claude

using LinkedInOptimizer.Domain.Entities;

namespace LinkedInOptimizer.Application.Common.Interfaces;

public interface IRewriteRepository
{
    Task<Rewrite?> GetByAnalysisIdAsync(Guid analysisId, CancellationToken ct);
}
