// (C) Generated by Claude
namespace LinkedInOptimizer.Infrastructure.Options;

public record CloudinaryOptions
{
    public string CloudName { get; init; } = string.Empty;
    public string ApiKey { get; init; } = string.Empty;
    public string ApiSecret { get; init; } = string.Empty;
}
