// (C) Generated by Claude
namespace LinkedInOptimizer.Infrastructure.Options;

public record PaystackOptions
{
    public string SecretKey { get; init; } = string.Empty;
    public string PublicKey { get; init; } = string.Empty;
    public int AmountKobo { get; init; } = 500000; // ₦5,000
}
