// (C) Generated by Claude

namespace LinkedInOptimizer.Domain.ValueObjects;

public enum AnalysisStatusValue
{
    Scored,
    Generating,
    Complete,
    Failed
}

public record AnalysisStatus
{
    public AnalysisStatusValue Value { get; }

    private AnalysisStatus(AnalysisStatusValue value) => Value = value;

    public static AnalysisStatus Scored => new(AnalysisStatusValue.Scored);
    public static AnalysisStatus Generating => new(AnalysisStatusValue.Generating);
    public static AnalysisStatus Complete => new(AnalysisStatusValue.Complete);
    public static AnalysisStatus Failed => new(AnalysisStatusValue.Failed);

    public bool IsTerminal => Value is AnalysisStatusValue.Complete or AnalysisStatusValue.Failed;

    public override string ToString() => Value.ToString().ToLowerInvariant();
}
