// (C) Generated by Claude

using LinkedInOptimizer.Domain.Exceptions;

namespace LinkedInOptimizer.Domain.ValueObjects;

public record ProfileScore
{
    public int Value { get; }

    private ProfileScore(int value) => Value = value;

    public static ProfileScore From(int value)
    {
        if (value is < 0 or > 100)
            throw new BusinessRuleViolationException("ProfileScore must be between 0 and 100.");

        return new ProfileScore(value);
    }

    public static ProfileScore Zero => new(0);

    public bool IsStrong => Value >= 70;
    public bool IsWeak => Value < 40;

    public override string ToString() => Value.ToString();
}
