// (C) Generated by Claude

namespace LinkedInOptimizer.Domain.ValueObjects;

public enum TierLevel
{
    Free,
    Premium
}

public record Tier
{
    public TierLevel Level { get; }

    private Tier(TierLevel level) => Level = level;

    public static Tier Free => new(TierLevel.Free);
    public static Tier Premium => new(TierLevel.Premium);

    public bool IsPremium => Level == TierLevel.Premium;

    public Tier UpgradeToPremium() => Premium;

    public override string ToString() => Level.ToString().ToLowerInvariant();
}
