// (C) Generated by Claude

using System.Net;
using System.Net.Http.Json;
using System.Reflection;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using LinkedInOptimizer.Application.Common.Interfaces;
using LinkedInOptimizer.Infrastructure.Options;
using Microsoft.Extensions.Configuration;
using Polly;
using Polly.Extensions.Http;

namespace LinkedInOptimizer.Infrastructure.Ai;

public sealed class ClaudeClient : IClaudeClient
{
    private const string AnthropicApiUrl = "https://api.anthropic.com/v1/messages";
    private const string AnthropicVersion = "2023-06-01";

    private readonly IHttpClientFactory _httpClientFactory;
    private readonly AnthropicOptions _options;
    private readonly IAsyncPolicy<HttpResponseMessage> _retryPolicy;

    public ClaudeClient(IHttpClientFactory httpClientFactory, IConfiguration configuration)
    {
        _httpClientFactory = httpClientFactory;
        _options = configuration.GetSection("Anthropic").Get<AnthropicOptions>() ?? new AnthropicOptions();
        _retryPolicy = HttpPolicyExtensions
            .HandleTransientHttpError()
            .OrResult(r => r.StatusCode == (HttpStatusCode)429)
            .WaitAndRetryAsync(3, attempt => TimeSpan.FromSeconds(Math.Pow(2, attempt - 1)));
    }

    public async Task<string> GenerateHeadlinesAsync(string profileJson, string cvJson, CancellationToken ct)
    {
        var prompt = await LoadPromptAsync("headlines", profileJson, cvJson);
        return await CallClaudeAsync(prompt, ct);
    }

    public async Task<string> GenerateAboutAsync(string profileJson, string cvJson, CancellationToken ct)
    {
        var prompt = await LoadPromptAsync("about", profileJson, cvJson);
        return await CallClaudeAsync(prompt, ct);
    }

    public async Task<string> GenerateExperienceAsync(string profileJson, string cvJson, CancellationToken ct)
    {
        var prompt = await LoadPromptAsync("experience", profileJson, cvJson);
        return await CallClaudeAsync(prompt, ct);
    }

    public async Task<string> GenerateAddonsAsync(string profileJson, string cvJson, CancellationToken ct)
    {
        var prompt = await LoadPromptAsync("addons", profileJson, cvJson);
        return await CallClaudeAsync(prompt, ct);
    }

    private static async Task<string> LoadPromptAsync(string name, string profileJson, string cvJson)
    {
        var resourceName = $"LinkedInOptimizer.Infrastructure.Ai.Prompts.{name}.txt";
        var assembly = Assembly.GetExecutingAssembly();
        using var stream = assembly.GetManifestResourceStream(resourceName)
            ?? throw new InvalidOperationException($"Embedded resource '{resourceName}' not found.");
        using var reader = new StreamReader(stream, Encoding.UTF8);
        var template = await reader.ReadToEndAsync();
        return template
            .Replace("{{PROFILE}}", profileJson)
            .Replace("{{CV}}", cvJson);
    }

    private async Task<string> CallClaudeAsync(string prompt, CancellationToken ct)
    {
        var client = _httpClientFactory.CreateClient();

        var requestBody = new
        {
            model = _options.Model,
            max_tokens = 2048,
            messages = new[]
            {
                new { role = "user", content = prompt }
            }
        };

        var json = JsonSerializer.Serialize(requestBody);

        HttpResponseMessage response = await _retryPolicy.ExecuteAsync(async () =>
        {
            using var request = new HttpRequestMessage(HttpMethod.Post, AnthropicApiUrl);
            request.Headers.Add("x-api-key", _options.ApiKey);
            request.Headers.Add("anthropic-version", AnthropicVersion);
            request.Content = new StringContent(json, Encoding.UTF8, "application/json");
            return await client.SendAsync(request, ct);
        });

        if (!response.IsSuccessStatusCode)
        {
            var errorBody = await response.Content.ReadAsStringAsync(ct);
            throw new InvalidOperationException(
                $"Anthropic API returned {(int)response.StatusCode}: {errorBody}");
        }

        var responseJson = await response.Content.ReadAsStringAsync(ct);
        using var doc = JsonDocument.Parse(responseJson);

        var text = doc.RootElement
            .GetProperty("content")[0]
            .GetProperty("text")
            .GetString();

        return text ?? throw new InvalidOperationException("Anthropic API returned an empty text response.");
    }
}
