// (C) Generated by Claude

using LinkedInOptimizer.Application.Common.Dtos;
using LinkedInOptimizer.Application.Common.Interfaces;
using LinkedInOptimizer.Domain.Exceptions;
using MediatR;

namespace LinkedInOptimizer.Application.Auth;

public record LoginCommand(string Email, string Password) : IRequest<AuthDto>;

public class LoginCommandHandler : IRequestHandler<LoginCommand, AuthDto>
{
    private readonly IUserRepository _userRepository;
    private readonly IPasswordHasher _passwordHasher;
    private readonly IJwtTokenService _jwtTokenService;

    public LoginCommandHandler(
        IUserRepository userRepository,
        IPasswordHasher passwordHasher,
        IJwtTokenService jwtTokenService)
    {
        _userRepository = userRepository;
        _passwordHasher = passwordHasher;
        _jwtTokenService = jwtTokenService;
    }

    public async Task<AuthDto> Handle(LoginCommand command, CancellationToken cancellationToken)
    {
        var user = await _userRepository.GetByEmailAsync(command.Email, cancellationToken);

        if (user is null)
            throw new BusinessRuleViolationException("Invalid credentials.");

        if (!_passwordHasher.Verify(command.Password, user.PasswordHash))
            throw new BusinessRuleViolationException("Invalid credentials.");

        var accessToken = _jwtTokenService.GenerateAccessToken(user);
        var refreshToken = _jwtTokenService.GenerateRefreshToken();

        return new AuthDto(accessToken, refreshToken);
    }
}
