// (C) Generated by Claude

using System.Security.Claims;
using LinkedInOptimizer.Application.Common.Dtos;
using LinkedInOptimizer.Application.Common.Interfaces;
using LinkedInOptimizer.Domain.Exceptions;
using MediatR;

namespace LinkedInOptimizer.Application.Auth;

public record RefreshTokenCommand(string RefreshToken) : IRequest<AuthDto>;

public class RefreshTokenCommandHandler : IRequestHandler<RefreshTokenCommand, AuthDto>
{
    private readonly IJwtTokenService _jwtTokenService;
    private readonly IUserRepository _userRepository;

    public RefreshTokenCommandHandler(
        IJwtTokenService jwtTokenService,
        IUserRepository userRepository)
    {
        _jwtTokenService = jwtTokenService;
        _userRepository = userRepository;
    }

    public async Task<AuthDto> Handle(RefreshTokenCommand command, CancellationToken cancellationToken)
    {
        // 1. Validate the refresh token — returns null if invalid or expired
        ClaimsPrincipal? principal = _jwtTokenService.ValidateRefreshToken(command.RefreshToken);
        if (principal is null)
            throw new BusinessRuleViolationException("Invalid or expired refresh token.");

        // 2. Extract user id from claims
        var userIdString = principal.FindFirst(ClaimTypes.NameIdentifier)?.Value;
        if (!Guid.TryParse(userIdString, out var userId))
            throw new BusinessRuleViolationException("Invalid or expired refresh token.");

        // 3. Load user from repository
        var user = await _userRepository.GetByIdAsync(userId, cancellationToken);
        if (user is null)
            throw new BusinessRuleViolationException("Invalid or expired refresh token.");

        // 4. Generate new access token
        var accessToken = _jwtTokenService.GenerateAccessToken(user);

        // 5. Rotate refresh token
        var newRefreshToken = _jwtTokenService.GenerateRefreshToken();

        // 6. Return new tokens
        return new AuthDto(accessToken, newRefreshToken);
    }
}
