// (C) Generated by Claude

using LinkedInOptimizer.Application.Common.Dtos;
using LinkedInOptimizer.Application.Common.Interfaces;
using LinkedInOptimizer.Domain.Entities;
using LinkedInOptimizer.Domain.Exceptions;
using MediatR;

namespace LinkedInOptimizer.Application.Auth;

public record SignupCommand(string Email, string Password) : IRequest<AuthDto>;

public class SignupCommandHandler : IRequestHandler<SignupCommand, AuthDto>
{
    private readonly IUserRepository _userRepository;
    private readonly IUnitOfWork _unitOfWork;
    private readonly IPasswordHasher _passwordHasher;
    private readonly IJwtTokenService _jwtTokenService;

    public SignupCommandHandler(
        IUserRepository userRepository,
        IUnitOfWork unitOfWork,
        IPasswordHasher passwordHasher,
        IJwtTokenService jwtTokenService)
    {
        _userRepository = userRepository;
        _unitOfWork = unitOfWork;
        _passwordHasher = passwordHasher;
        _jwtTokenService = jwtTokenService;
    }

    public async Task<AuthDto> Handle(SignupCommand command, CancellationToken cancellationToken)
    {
        // 1. Check for existing user by email
        var existing = await _userRepository.GetByEmailAsync(command.Email, cancellationToken);
        if (existing is not null)
            throw new BusinessRuleViolationException("Email is already registered.");

        // 2. Hash password
        var hash = _passwordHasher.Hash(command.Password);

        // 3. Create user entity
        var user = User.Create(command.Email, hash);

        // 4. Persist user
        await _userRepository.AddAsync(user, cancellationToken);

        // 5. Save changes
        await _unitOfWork.SaveChangesAsync(cancellationToken);

        // 6. Generate tokens
        var accessToken = _jwtTokenService.GenerateAccessToken(user);
        var refreshToken = _jwtTokenService.GenerateRefreshToken();

        // 7. Return AuthDto
        return new AuthDto(accessToken, refreshToken);
    }
}
