// (C) Generated by Claude

using LinkedInOptimizer.Application.Common.Interfaces;
using LinkedInOptimizer.Domain.Entities;

namespace LinkedInOptimizer.Infrastructure.Persistence.Repositories;

public class AnalysisRepository : IAnalysisRepository
{
    private readonly AppDbContext _db;
    public AnalysisRepository(AppDbContext db) => _db = db;

    public async Task AddAsync(Analysis analysis, CancellationToken ct)
        => await _db.Analyses.AddAsync(analysis, ct);

    public Task<Analysis?> GetByIdAsync(Guid id, CancellationToken ct)
        => _db.Analyses.FindAsync([id], ct).AsTask();
}
