// (C) Generated by Claude

using LinkedInOptimizer.Application.Common.Interfaces;
using LinkedInOptimizer.Domain.Entities;
using Microsoft.EntityFrameworkCore;

namespace LinkedInOptimizer.Infrastructure.Persistence.Repositories;

public class CvRepository : ICvRepository
{
    private readonly AppDbContext _db;
    public CvRepository(AppDbContext db) => _db = db;

    public Task<Cv?> GetByIdAsync(Guid id, CancellationToken ct = default)
        => _db.Cvs.FindAsync([id], ct).AsTask();

    public Task<Cv?> GetByUserIdAsync(Guid userId, CancellationToken ct)
        => _db.Cvs.FirstOrDefaultAsync(c => c.UserId == userId, ct);

    public async Task AddAsync(Cv cv, CancellationToken ct)
        => await _db.Cvs.AddAsync(cv, ct);

    public Task RemoveAsync(Cv cv, CancellationToken ct)
    {
        _db.Cvs.Remove(cv);
        return Task.CompletedTask;
    }
}
