// (C) Generated by Claude

using LinkedInOptimizer.Application.Common.Interfaces;
using LinkedInOptimizer.Domain.Entities;
using Microsoft.EntityFrameworkCore;

namespace LinkedInOptimizer.Infrastructure.Persistence.Repositories;

public class PaymentRepository : IPaymentRepository
{
    private readonly AppDbContext _db;
    public PaymentRepository(AppDbContext db) => _db = db;

    public async Task AddAsync(Payment payment, CancellationToken ct)
        => await _db.Payments.AddAsync(payment, ct);

    public Task<Payment?> GetByReferenceAsync(string reference, CancellationToken ct)
        => _db.Payments.FirstOrDefaultAsync(p => p.PaystackReference == reference, ct);
}
