// (C) Generated by Claude

using LinkedInOptimizer.Application.Common.Interfaces;
using LinkedInOptimizer.Domain.Entities;

namespace LinkedInOptimizer.Infrastructure.Persistence.Repositories;

public class ProfileRepository : IProfileRepository
{
    private readonly AppDbContext _db;
    public ProfileRepository(AppDbContext db) => _db = db;

    public async Task AddAsync(Profile profile, CancellationToken ct)
        => await _db.Profiles.AddAsync(profile, ct);

    public Task<Profile?> GetByIdAsync(Guid id, CancellationToken ct)
        => _db.Profiles.FindAsync([id], ct).AsTask();
}
