// (C) Generated by Claude

using LinkedInOptimizer.Application.Common.Interfaces;
using LinkedInOptimizer.Domain.Entities;
using Microsoft.EntityFrameworkCore;

namespace LinkedInOptimizer.Infrastructure.Persistence.Repositories;

public class RewriteRepository : IRewriteRepository
{
    private readonly AppDbContext _db;
    public RewriteRepository(AppDbContext db) => _db = db;

    public Task<Rewrite?> GetByAnalysisIdAsync(Guid analysisId, CancellationToken ct)
        => _db.Rewrites.FirstOrDefaultAsync(r => r.AnalysisId == analysisId, ct);
}
